//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZCameraTester.CameraConfiguration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1", ConfigurationName="CameraConfiguration.CameraConfigurationPortType")]
    public interface CameraConfigurationPortType {
        
        // CODEGEN: Parameter 'cameraConfig' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:CameraConfiguration:1#GetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cameraConfig")]
        PTZCameraTester.CameraConfiguration.GetConfigurationResponse GetConfiguration(PTZCameraTester.CameraConfiguration.GetConfigurationRequest request);
        
        // CODEGEN: Parameter 'cameraConfig' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:CameraConfiguration:1#SetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.CameraConfiguration.SetConfigurationResponse SetConfiguration(PTZCameraTester.CameraConfiguration.SetConfigurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:CameraConfiguration:1#ResetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ResetConfiguration();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class CameraConfig : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VideoProperties videopropertiesField;
        
        private CameraConfigVideoQuality videoQualityField;
        
        private int coaxModeField;
        
        private bool coaxModeFieldSpecified;
        
        private ConfigurableInt controlModeField;
        
        private int cameraAddressField;
        
        private ConfigurableInt cameraTypeField;
        
        private Distinguishers distinguishersField;
        
        private int motionDetectionEnableField;
        
        private int motionAlarmDwellSecsField;
        
        private bool motionAlarmDwellSecsFieldSpecified;
        
        private int audioEnableField;
        
        private int terminationField;
        
        private int audioHardwareInputField;
        
        private bool audioHardwareInputFieldSpecified;
        
        private int ttlField;
        
        private int packetsizeField;
        
        private VideoPair videopairField;
        
        private int localQualityField;
        
        private CameraConfigMaxUnicast maxUnicastField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public VideoProperties videoproperties {
            get {
                return this.videopropertiesField;
            }
            set {
                this.videopropertiesField = value;
                this.RaisePropertyChanged("videoproperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CameraConfigVideoQuality videoQuality {
            get {
                return this.videoQualityField;
            }
            set {
                this.videoQualityField = value;
                this.RaisePropertyChanged("videoQuality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int coaxMode {
            get {
                return this.coaxModeField;
            }
            set {
                this.coaxModeField = value;
                this.RaisePropertyChanged("coaxMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coaxModeSpecified {
            get {
                return this.coaxModeFieldSpecified;
            }
            set {
                this.coaxModeFieldSpecified = value;
                this.RaisePropertyChanged("coaxModeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ConfigurableInt controlMode {
            get {
                return this.controlModeField;
            }
            set {
                this.controlModeField = value;
                this.RaisePropertyChanged("controlMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int cameraAddress {
            get {
                return this.cameraAddressField;
            }
            set {
                this.cameraAddressField = value;
                this.RaisePropertyChanged("cameraAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ConfigurableInt cameraType {
            get {
                return this.cameraTypeField;
            }
            set {
                this.cameraTypeField = value;
                this.RaisePropertyChanged("cameraType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Distinguishers distinguishers {
            get {
                return this.distinguishersField;
            }
            set {
                this.distinguishersField = value;
                this.RaisePropertyChanged("distinguishers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int motionDetectionEnable {
            get {
                return this.motionDetectionEnableField;
            }
            set {
                this.motionDetectionEnableField = value;
                this.RaisePropertyChanged("motionDetectionEnable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int motionAlarmDwellSecs {
            get {
                return this.motionAlarmDwellSecsField;
            }
            set {
                this.motionAlarmDwellSecsField = value;
                this.RaisePropertyChanged("motionAlarmDwellSecs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool motionAlarmDwellSecsSpecified {
            get {
                return this.motionAlarmDwellSecsFieldSpecified;
            }
            set {
                this.motionAlarmDwellSecsFieldSpecified = value;
                this.RaisePropertyChanged("motionAlarmDwellSecsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int audioEnable {
            get {
                return this.audioEnableField;
            }
            set {
                this.audioEnableField = value;
                this.RaisePropertyChanged("audioEnable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int termination {
            get {
                return this.terminationField;
            }
            set {
                this.terminationField = value;
                this.RaisePropertyChanged("termination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int audioHardwareInput {
            get {
                return this.audioHardwareInputField;
            }
            set {
                this.audioHardwareInputField = value;
                this.RaisePropertyChanged("audioHardwareInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool audioHardwareInputSpecified {
            get {
                return this.audioHardwareInputFieldSpecified;
            }
            set {
                this.audioHardwareInputFieldSpecified = value;
                this.RaisePropertyChanged("audioHardwareInputSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
                this.RaisePropertyChanged("ttl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int packetsize {
            get {
                return this.packetsizeField;
            }
            set {
                this.packetsizeField = value;
                this.RaisePropertyChanged("packetsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public VideoPair videopair {
            get {
                return this.videopairField;
            }
            set {
                this.videopairField = value;
                this.RaisePropertyChanged("videopair");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int localQuality {
            get {
                return this.localQualityField;
            }
            set {
                this.localQualityField = value;
                this.RaisePropertyChanged("localQuality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public CameraConfigMaxUnicast maxUnicast {
            get {
                return this.maxUnicastField;
            }
            set {
                this.maxUnicastField = value;
                this.RaisePropertyChanged("maxUnicast");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class VideoProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MVElement brightnessField;
        
        private MVElement contrastField;
        
        private MVElement hueField;
        
        private MVElement saturationField;
        
        private int filterLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public MVElement brightness {
            get {
                return this.brightnessField;
            }
            set {
                this.brightnessField = value;
                this.RaisePropertyChanged("brightness");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MVElement contrast {
            get {
                return this.contrastField;
            }
            set {
                this.contrastField = value;
                this.RaisePropertyChanged("contrast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public MVElement hue {
            get {
                return this.hueField;
            }
            set {
                this.hueField = value;
                this.RaisePropertyChanged("hue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public MVElement saturation {
            get {
                return this.saturationField;
            }
            set {
                this.saturationField = value;
                this.RaisePropertyChanged("saturation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int filterLevel {
            get {
                return this.filterLevelField;
            }
            set {
                this.filterLevelField = value;
                this.RaisePropertyChanged("filterLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class MVElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int modeField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class VideoChannel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double framerateField;
        
        private int bitrateField;
        
        private string formatField;
        
        private int videosizeField;
        
        private int tvformatField;
        
        private int pruneStoredVideoField;
        
        private bool pruneStoredVideoFieldSpecified;
        
        private double gopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double framerate {
            get {
                return this.framerateField;
            }
            set {
                this.framerateField = value;
                this.RaisePropertyChanged("framerate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int bitrate {
            get {
                return this.bitrateField;
            }
            set {
                this.bitrateField = value;
                this.RaisePropertyChanged("bitrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int videosize {
            get {
                return this.videosizeField;
            }
            set {
                this.videosizeField = value;
                this.RaisePropertyChanged("videosize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tvformat {
            get {
                return this.tvformatField;
            }
            set {
                this.tvformatField = value;
                this.RaisePropertyChanged("tvformat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int pruneStoredVideo {
            get {
                return this.pruneStoredVideoField;
            }
            set {
                this.pruneStoredVideoField = value;
                this.RaisePropertyChanged("pruneStoredVideo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pruneStoredVideoSpecified {
            get {
                return this.pruneStoredVideoFieldSpecified;
            }
            set {
                this.pruneStoredVideoFieldSpecified = value;
                this.RaisePropertyChanged("pruneStoredVideoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double gop {
            get {
                return this.gopField;
            }
            set {
                this.gopField = value;
                this.RaisePropertyChanged("gop");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class VideoPair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private VideoChannel primaryField;
        
        private VideoChannel secondaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public VideoChannel primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("primary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public VideoChannel secondary {
            get {
                return this.secondaryField;
            }
            set {
                this.secondaryField = value;
                this.RaisePropertyChanged("secondary");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class Distinguishers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int viewobjectField;
        
        private bool viewobjectFieldSpecified;
        
        private int domeField;
        
        private bool domeFieldSpecified;
        
        private int ptzField;
        
        private bool ptzFieldSpecified;
        
        private int fixedField;
        
        private bool fixedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int viewobject {
            get {
                return this.viewobjectField;
            }
            set {
                this.viewobjectField = value;
                this.RaisePropertyChanged("viewobject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool viewobjectSpecified {
            get {
                return this.viewobjectFieldSpecified;
            }
            set {
                this.viewobjectFieldSpecified = value;
                this.RaisePropertyChanged("viewobjectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int dome {
            get {
                return this.domeField;
            }
            set {
                this.domeField = value;
                this.RaisePropertyChanged("dome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool domeSpecified {
            get {
                return this.domeFieldSpecified;
            }
            set {
                this.domeFieldSpecified = value;
                this.RaisePropertyChanged("domeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ptz {
            get {
                return this.ptzField;
            }
            set {
                this.ptzField = value;
                this.RaisePropertyChanged("ptz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ptzSpecified {
            get {
                return this.ptzFieldSpecified;
            }
            set {
                this.ptzFieldSpecified = value;
                this.RaisePropertyChanged("ptzSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int @fixed {
            get {
                return this.fixedField;
            }
            set {
                this.fixedField = value;
                this.RaisePropertyChanged("fixed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixedSpecified {
            get {
                return this.fixedFieldSpecified;
            }
            set {
                this.fixedFieldSpecified = value;
                this.RaisePropertyChanged("fixedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class ConfigurableInt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int configurableField;
        
        private bool configurableFieldSpecified;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int configurable {
            get {
                return this.configurableField;
            }
            set {
                this.configurableField = value;
                this.RaisePropertyChanged("configurable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool configurableSpecified {
            get {
                return this.configurableFieldSpecified;
            }
            set {
                this.configurableFieldSpecified = value;
                this.RaisePropertyChanged("configurableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class CameraConfigVideoQuality : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int localField;
        
        private bool localFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
                this.RaisePropertyChanged("local");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localSpecified {
            get {
                return this.localFieldSpecified;
            }
            set {
                this.localFieldSpecified = value;
                this.RaisePropertyChanged("localSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1")]
    public partial class CameraConfigMaxUnicast : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mcastFailoverField;
        
        private bool mcastFailoverFieldSpecified;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int mcastFailover {
            get {
                return this.mcastFailoverField;
            }
            set {
                this.mcastFailoverField = value;
                this.RaisePropertyChanged("mcastFailover");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mcastFailoverSpecified {
            get {
                return this.mcastFailoverFieldSpecified;
            }
            set {
                this.mcastFailoverFieldSpecified = value;
                this.RaisePropertyChanged("mcastFailoverSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:CameraConfiguration:1", IsWrapped=true)]
    public partial class GetConfigurationRequest {
        
        public GetConfigurationRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:CameraConfiguration:1", IsWrapped=true)]
    public partial class GetConfigurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.CameraConfiguration.CameraConfig cameraConfig;
        
        public GetConfigurationResponse() {
        }
        
        public GetConfigurationResponse(PTZCameraTester.CameraConfiguration.CameraConfig cameraConfig) {
            this.cameraConfig = cameraConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:CameraConfiguration:1", IsWrapped=true)]
    public partial class SetConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:CameraConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.CameraConfiguration.CameraConfig cameraConfig;
        
        public SetConfigurationRequest() {
        }
        
        public SetConfigurationRequest(PTZCameraTester.CameraConfiguration.CameraConfig cameraConfig) {
            this.cameraConfig = cameraConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:CameraConfiguration:1", IsWrapped=true)]
    public partial class SetConfigurationResponse {
        
        public SetConfigurationResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CameraConfigurationPortTypeChannel : PTZCameraTester.CameraConfiguration.CameraConfigurationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CameraConfigurationPortTypeClient : System.ServiceModel.ClientBase<PTZCameraTester.CameraConfiguration.CameraConfigurationPortType>, PTZCameraTester.CameraConfiguration.CameraConfigurationPortType {
        
        public CameraConfigurationPortTypeClient() {
        }
        
        public CameraConfigurationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CameraConfigurationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraConfigurationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraConfigurationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.CameraConfiguration.GetConfigurationResponse PTZCameraTester.CameraConfiguration.CameraConfigurationPortType.GetConfiguration(PTZCameraTester.CameraConfiguration.GetConfigurationRequest request) {
            return base.Channel.GetConfiguration(request);
        }
        
        public PTZCameraTester.CameraConfiguration.CameraConfig GetConfiguration() {
            PTZCameraTester.CameraConfiguration.GetConfigurationRequest inValue = new PTZCameraTester.CameraConfiguration.GetConfigurationRequest();
            PTZCameraTester.CameraConfiguration.GetConfigurationResponse retVal = ((PTZCameraTester.CameraConfiguration.CameraConfigurationPortType)(this)).GetConfiguration(inValue);
            return retVal.cameraConfig;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.CameraConfiguration.SetConfigurationResponse PTZCameraTester.CameraConfiguration.CameraConfigurationPortType.SetConfiguration(PTZCameraTester.CameraConfiguration.SetConfigurationRequest request) {
            return base.Channel.SetConfiguration(request);
        }
        
        public void SetConfiguration(PTZCameraTester.CameraConfiguration.CameraConfig cameraConfig) {
            PTZCameraTester.CameraConfiguration.SetConfigurationRequest inValue = new PTZCameraTester.CameraConfiguration.SetConfigurationRequest();
            inValue.cameraConfig = cameraConfig;
            PTZCameraTester.CameraConfiguration.SetConfigurationResponse retVal = ((PTZCameraTester.CameraConfiguration.CameraConfigurationPortType)(this)).SetConfiguration(inValue);
        }
        
        public void ResetConfiguration() {
            base.Channel.ResetConfiguration();
        }
    }
}
