//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZCameraTester.ScriptControl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", ConfigurationName="ScriptControl.ScriptControlPortType")]
    public interface ScriptControlPortType {
        
        // CODEGEN: Parameter 'scriptName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#BeginScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.ScriptControl.BeginScriptResponse BeginScript(PTZCameraTester.ScriptControl.BeginScriptRequest request);
        
        // CODEGEN: Parameter 'scriptName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#EndScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.ScriptControl.EndScriptResponse EndScript(PTZCameraTester.ScriptControl.EndScriptRequest request);
        
        // CODEGEN: Parameter 'scriptName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#CancelScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.ScriptControl.CancelScriptResponse CancelScript(PTZCameraTester.ScriptControl.CancelScriptRequest request);
        
        // CODEGEN: Parameter 'scriptName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#DeleteScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.ScriptControl.DeleteScriptResponse DeleteScript(PTZCameraTester.ScriptControl.DeleteScriptRequest request);
        
        // CODEGEN: Parameter 'scriptList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#QueryScripts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="scriptList")]
        PTZCameraTester.ScriptControl.QueryScriptsResponse QueryScripts(PTZCameraTester.ScriptControl.QueryScriptsRequest request);
        
        // CODEGEN: Parameter 'pid' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#ExecuteScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pid")]
        PTZCameraTester.ScriptControl.ExecuteScriptResponse ExecuteScript(PTZCameraTester.ScriptControl.ExecuteScriptRequest request);
        
        // CODEGEN: Parameter 'scriptName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#HaltScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.ScriptControl.HaltScriptResponse HaltScript(PTZCameraTester.ScriptControl.HaltScriptRequest request);
        
        // CODEGEN: Parameter 'scriptId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#UploadScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="scriptId")]
        PTZCameraTester.ScriptControl.UploadScriptResponse UploadScript(PTZCameraTester.ScriptControl.UploadScriptRequest request);
        
        // CODEGEN: Parameter 'scriptURL' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#DownloadScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="scriptURL")]
        PTZCameraTester.ScriptControl.DownloadScriptResponse DownloadScript(PTZCameraTester.ScriptControl.DownloadScriptRequest request);
        
        // CODEGEN: Parameter 'scriptName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#SetScriptOwner", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.ScriptControl.SetScriptOwnerResponse SetScriptOwner(PTZCameraTester.ScriptControl.SetScriptOwnerRequest request);
        
        // CODEGEN: Parameter 'scriptActionList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:ScriptControl:1#QueryActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.ScriptControl.QueryActionsResponse QueryActions(PTZCameraTester.ScriptControl.QueryActionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class BeginScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        public BeginScriptRequest() {
        }
        
        public BeginScriptRequest(string scriptName) {
            this.scriptName = scriptName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class BeginScriptResponse {
        
        public BeginScriptResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class EndScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        public EndScriptRequest() {
        }
        
        public EndScriptRequest(string scriptName) {
            this.scriptName = scriptName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EndScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class EndScriptResponse {
        
        public EndScriptResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class CancelScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        public CancelScriptRequest() {
        }
        
        public CancelScriptRequest(string scriptName) {
            this.scriptName = scriptName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class CancelScriptResponse {
        
        public CancelScriptResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class DeleteScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        public DeleteScriptRequest() {
        }
        
        public DeleteScriptRequest(string scriptName) {
            this.scriptName = scriptName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class DeleteScriptResponse {
        
        public DeleteScriptResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1")]
    public partial class ScriptQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string descriptionField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int ownerField;
        
        private bool ownerFieldSpecified;
        
        private bool executingField;
        
        private bool executingFieldSpecified;
        
        private string queryIdField;
        
        private int nextEntryField;
        
        private bool nextEntryFieldSpecified;
        
        private int maxEntriesField;
        
        private bool maxEntriesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ownerSpecified {
            get {
                return this.ownerFieldSpecified;
            }
            set {
                this.ownerFieldSpecified = value;
                this.RaisePropertyChanged("ownerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool executing {
            get {
                return this.executingField;
            }
            set {
                this.executingField = value;
                this.RaisePropertyChanged("executing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool executingSpecified {
            get {
                return this.executingFieldSpecified;
            }
            set {
                this.executingFieldSpecified = value;
                this.RaisePropertyChanged("executingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string queryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
                this.RaisePropertyChanged("queryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int nextEntry {
            get {
                return this.nextEntryField;
            }
            set {
                this.nextEntryField = value;
                this.RaisePropertyChanged("nextEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nextEntrySpecified {
            get {
                return this.nextEntryFieldSpecified;
            }
            set {
                this.nextEntryFieldSpecified = value;
                this.RaisePropertyChanged("nextEntrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int maxEntries {
            get {
                return this.maxEntriesField;
            }
            set {
                this.maxEntriesField = value;
                this.RaisePropertyChanged("maxEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxEntriesSpecified {
            get {
                return this.maxEntriesFieldSpecified;
            }
            set {
                this.maxEntriesFieldSpecified = value;
                this.RaisePropertyChanged("maxEntriesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1")]
    public partial class Argument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1")]
    public partial class ScriptAction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private Argument[] argumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("argument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Argument[] arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
                this.RaisePropertyChanged("arguments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1")]
    public partial class ScriptActionList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ScriptAction[] actionsField;
        
        private string queryIdField;
        
        private int nextEntryField;
        
        private bool nextEntryFieldSpecified;
        
        private int maxEntriesField;
        
        private bool maxEntriesFieldSpecified;
        
        private int maxPresetsField;
        
        private bool maxPresetsFieldSpecified;
        
        private int maxPatternsField;
        
        private bool maxPatternsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("scriptActions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ScriptAction[] actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
                this.RaisePropertyChanged("actions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string queryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
                this.RaisePropertyChanged("queryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int nextEntry {
            get {
                return this.nextEntryField;
            }
            set {
                this.nextEntryField = value;
                this.RaisePropertyChanged("nextEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nextEntrySpecified {
            get {
                return this.nextEntryFieldSpecified;
            }
            set {
                this.nextEntryFieldSpecified = value;
                this.RaisePropertyChanged("nextEntrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int maxEntries {
            get {
                return this.maxEntriesField;
            }
            set {
                this.maxEntriesField = value;
                this.RaisePropertyChanged("maxEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxEntriesSpecified {
            get {
                return this.maxEntriesFieldSpecified;
            }
            set {
                this.maxEntriesFieldSpecified = value;
                this.RaisePropertyChanged("maxEntriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int maxPresets {
            get {
                return this.maxPresetsField;
            }
            set {
                this.maxPresetsField = value;
                this.RaisePropertyChanged("maxPresets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPresetsSpecified {
            get {
                return this.maxPresetsFieldSpecified;
            }
            set {
                this.maxPresetsFieldSpecified = value;
                this.RaisePropertyChanged("maxPresetsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int maxPatterns {
            get {
                return this.maxPatternsField;
            }
            set {
                this.maxPatternsField = value;
                this.RaisePropertyChanged("maxPatterns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPatternsSpecified {
            get {
                return this.maxPatternsFieldSpecified;
            }
            set {
                this.maxPatternsFieldSpecified = value;
                this.RaisePropertyChanged("maxPatternsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1")]
    public partial class Script : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string descriptionField;
        
        private int idField;
        
        private string ownerField;
        
        private string[] pidsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] pids {
            get {
                return this.pidsField;
            }
            set {
                this.pidsField = value;
                this.RaisePropertyChanged("pids");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1")]
    public partial class ScriptList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Script[] scriptsField;
        
        private ScriptListQueryId queryIdField;
        
        private int nextEntryField;
        
        private bool nextEntryFieldSpecified;
        
        private int maxEntriesField;
        
        private bool maxEntriesFieldSpecified;
        
        private int maxPresetsField;
        
        private bool maxPresetsFieldSpecified;
        
        private int maxPatternsField;
        
        private bool maxPatternsFieldSpecified;
        
        private int totalEntriesField;
        
        private bool totalEntriesFieldSpecified;
        
        private string resultURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("script", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Script[] scripts {
            get {
                return this.scriptsField;
            }
            set {
                this.scriptsField = value;
                this.RaisePropertyChanged("scripts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ScriptListQueryId queryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
                this.RaisePropertyChanged("queryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int nextEntry {
            get {
                return this.nextEntryField;
            }
            set {
                this.nextEntryField = value;
                this.RaisePropertyChanged("nextEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nextEntrySpecified {
            get {
                return this.nextEntryFieldSpecified;
            }
            set {
                this.nextEntryFieldSpecified = value;
                this.RaisePropertyChanged("nextEntrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int maxEntries {
            get {
                return this.maxEntriesField;
            }
            set {
                this.maxEntriesField = value;
                this.RaisePropertyChanged("maxEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxEntriesSpecified {
            get {
                return this.maxEntriesFieldSpecified;
            }
            set {
                this.maxEntriesFieldSpecified = value;
                this.RaisePropertyChanged("maxEntriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int maxPresets {
            get {
                return this.maxPresetsField;
            }
            set {
                this.maxPresetsField = value;
                this.RaisePropertyChanged("maxPresets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPresetsSpecified {
            get {
                return this.maxPresetsFieldSpecified;
            }
            set {
                this.maxPresetsFieldSpecified = value;
                this.RaisePropertyChanged("maxPresetsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int maxPatterns {
            get {
                return this.maxPatternsField;
            }
            set {
                this.maxPatternsField = value;
                this.RaisePropertyChanged("maxPatterns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPatternsSpecified {
            get {
                return this.maxPatternsFieldSpecified;
            }
            set {
                this.maxPatternsFieldSpecified = value;
                this.RaisePropertyChanged("maxPatternsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int totalEntries {
            get {
                return this.totalEntriesField;
            }
            set {
                this.totalEntriesField = value;
                this.RaisePropertyChanged("totalEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalEntriesSpecified {
            get {
                return this.totalEntriesFieldSpecified;
            }
            set {
                this.totalEntriesFieldSpecified = value;
                this.RaisePropertyChanged("totalEntriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string resultURI {
            get {
                return this.resultURIField;
            }
            set {
                this.resultURIField = value;
                this.RaisePropertyChanged("resultURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-pelco-com:service:ScriptControl:1")]
    public partial class ScriptListQueryId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int timeoutField;
        
        private bool timeoutFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
                this.RaisePropertyChanged("timeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeoutSpecified {
            get {
                return this.timeoutFieldSpecified;
            }
            set {
                this.timeoutFieldSpecified = value;
                this.RaisePropertyChanged("timeoutSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryScripts", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class QueryScriptsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.ScriptControl.ScriptQuery scriptQuery;
        
        public QueryScriptsRequest() {
        }
        
        public QueryScriptsRequest(PTZCameraTester.ScriptControl.ScriptQuery scriptQuery) {
            this.scriptQuery = scriptQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryScriptsResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class QueryScriptsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.ScriptControl.ScriptList scriptList;
        
        public QueryScriptsResponse() {
        }
        
        public QueryScriptsResponse(PTZCameraTester.ScriptControl.ScriptList scriptList) {
            this.scriptList = scriptList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class ExecuteScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        public ExecuteScriptRequest() {
        }
        
        public ExecuteScriptRequest(string scriptName) {
            this.scriptName = scriptName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class ExecuteScriptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pid;
        
        public ExecuteScriptResponse() {
        }
        
        public ExecuteScriptResponse(int pid) {
            this.pid = pid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HaltScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class HaltScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pid;
        
        public HaltScriptRequest() {
        }
        
        public HaltScriptRequest(string scriptName, int pid) {
            this.scriptName = scriptName;
            this.pid = pid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HaltScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class HaltScriptResponse {
        
        public HaltScriptResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class UploadScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int overWrite;
        
        public UploadScriptRequest() {
        }
        
        public UploadScriptRequest(string scriptName, string description, string scriptURL, int timeOut, int overWrite) {
            this.scriptName = scriptName;
            this.description = description;
            this.scriptURL = scriptURL;
            this.timeOut = timeOut;
            this.overWrite = overWrite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class UploadScriptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int scriptId;
        
        public UploadScriptResponse() {
        }
        
        public UploadScriptResponse(int scriptId) {
            this.scriptId = scriptId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadScript", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class DownloadScriptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        public DownloadScriptRequest() {
        }
        
        public DownloadScriptRequest(string scriptName) {
            this.scriptName = scriptName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadScriptResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class DownloadScriptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeOut;
        
        public DownloadScriptResponse() {
        }
        
        public DownloadScriptResponse(string scriptURL, int timeOut) {
            this.scriptURL = scriptURL;
            this.timeOut = timeOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetScriptOwner", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class SetScriptOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scriptName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int userId;
        
        public SetScriptOwnerRequest() {
        }
        
        public SetScriptOwnerRequest(string scriptName, int userId) {
            this.scriptName = scriptName;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetScriptOwnerResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class SetScriptOwnerResponse {
        
        public SetScriptOwnerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryActions", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class QueryActionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.ScriptControl.ScriptActionList scriptActionList;
        
        public QueryActionsRequest() {
        }
        
        public QueryActionsRequest(PTZCameraTester.ScriptControl.ScriptActionList scriptActionList) {
            this.scriptActionList = scriptActionList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryActionsResponse", WrapperNamespace="urn:schemas-pelco-com:service:ScriptControl:1", IsWrapped=true)]
    public partial class QueryActionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:ScriptControl:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.ScriptControl.ScriptActionList scriptActionList;
        
        public QueryActionsResponse() {
        }
        
        public QueryActionsResponse(PTZCameraTester.ScriptControl.ScriptActionList scriptActionList) {
            this.scriptActionList = scriptActionList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScriptControlPortTypeChannel : PTZCameraTester.ScriptControl.ScriptControlPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScriptControlPortTypeClient : System.ServiceModel.ClientBase<PTZCameraTester.ScriptControl.ScriptControlPortType>, PTZCameraTester.ScriptControl.ScriptControlPortType {
        
        public ScriptControlPortTypeClient() {
        }
        
        public ScriptControlPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScriptControlPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScriptControlPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScriptControlPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.BeginScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.BeginScript(PTZCameraTester.ScriptControl.BeginScriptRequest request) {
            return base.Channel.BeginScript(request);
        }
        
        public void BeginScript(string scriptName) {
            PTZCameraTester.ScriptControl.BeginScriptRequest inValue = new PTZCameraTester.ScriptControl.BeginScriptRequest();
            inValue.scriptName = scriptName;
            PTZCameraTester.ScriptControl.BeginScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).BeginScript(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.EndScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.EndScript(PTZCameraTester.ScriptControl.EndScriptRequest request) {
            return base.Channel.EndScript(request);
        }
        
        public void EndScript(string scriptName) {
            PTZCameraTester.ScriptControl.EndScriptRequest inValue = new PTZCameraTester.ScriptControl.EndScriptRequest();
            inValue.scriptName = scriptName;
            PTZCameraTester.ScriptControl.EndScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).EndScript(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.CancelScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.CancelScript(PTZCameraTester.ScriptControl.CancelScriptRequest request) {
            return base.Channel.CancelScript(request);
        }
        
        public void CancelScript(string scriptName) {
            PTZCameraTester.ScriptControl.CancelScriptRequest inValue = new PTZCameraTester.ScriptControl.CancelScriptRequest();
            inValue.scriptName = scriptName;
            PTZCameraTester.ScriptControl.CancelScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).CancelScript(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.DeleteScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.DeleteScript(PTZCameraTester.ScriptControl.DeleteScriptRequest request) {
            return base.Channel.DeleteScript(request);
        }
        
        public void DeleteScript(string scriptName) {
            PTZCameraTester.ScriptControl.DeleteScriptRequest inValue = new PTZCameraTester.ScriptControl.DeleteScriptRequest();
            inValue.scriptName = scriptName;
            PTZCameraTester.ScriptControl.DeleteScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).DeleteScript(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.QueryScriptsResponse PTZCameraTester.ScriptControl.ScriptControlPortType.QueryScripts(PTZCameraTester.ScriptControl.QueryScriptsRequest request) {
            return base.Channel.QueryScripts(request);
        }
        
        public PTZCameraTester.ScriptControl.ScriptList QueryScripts(PTZCameraTester.ScriptControl.ScriptQuery scriptQuery) {
            PTZCameraTester.ScriptControl.QueryScriptsRequest inValue = new PTZCameraTester.ScriptControl.QueryScriptsRequest();
            inValue.scriptQuery = scriptQuery;
            PTZCameraTester.ScriptControl.QueryScriptsResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).QueryScripts(inValue);
            return retVal.scriptList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.ExecuteScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.ExecuteScript(PTZCameraTester.ScriptControl.ExecuteScriptRequest request) {
            return base.Channel.ExecuteScript(request);
        }
        
        public int ExecuteScript(string scriptName) {
            PTZCameraTester.ScriptControl.ExecuteScriptRequest inValue = new PTZCameraTester.ScriptControl.ExecuteScriptRequest();
            inValue.scriptName = scriptName;
            PTZCameraTester.ScriptControl.ExecuteScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).ExecuteScript(inValue);
            return retVal.pid;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.HaltScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.HaltScript(PTZCameraTester.ScriptControl.HaltScriptRequest request) {
            return base.Channel.HaltScript(request);
        }
        
        public void HaltScript(string scriptName, int pid) {
            PTZCameraTester.ScriptControl.HaltScriptRequest inValue = new PTZCameraTester.ScriptControl.HaltScriptRequest();
            inValue.scriptName = scriptName;
            inValue.pid = pid;
            PTZCameraTester.ScriptControl.HaltScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).HaltScript(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.UploadScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.UploadScript(PTZCameraTester.ScriptControl.UploadScriptRequest request) {
            return base.Channel.UploadScript(request);
        }
        
        public int UploadScript(string scriptName, string description, string scriptURL, int timeOut, int overWrite) {
            PTZCameraTester.ScriptControl.UploadScriptRequest inValue = new PTZCameraTester.ScriptControl.UploadScriptRequest();
            inValue.scriptName = scriptName;
            inValue.description = description;
            inValue.scriptURL = scriptURL;
            inValue.timeOut = timeOut;
            inValue.overWrite = overWrite;
            PTZCameraTester.ScriptControl.UploadScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).UploadScript(inValue);
            return retVal.scriptId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.DownloadScriptResponse PTZCameraTester.ScriptControl.ScriptControlPortType.DownloadScript(PTZCameraTester.ScriptControl.DownloadScriptRequest request) {
            return base.Channel.DownloadScript(request);
        }
        
        public string DownloadScript(string scriptName, out int timeOut) {
            PTZCameraTester.ScriptControl.DownloadScriptRequest inValue = new PTZCameraTester.ScriptControl.DownloadScriptRequest();
            inValue.scriptName = scriptName;
            PTZCameraTester.ScriptControl.DownloadScriptResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).DownloadScript(inValue);
            timeOut = retVal.timeOut;
            return retVal.scriptURL;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.SetScriptOwnerResponse PTZCameraTester.ScriptControl.ScriptControlPortType.SetScriptOwner(PTZCameraTester.ScriptControl.SetScriptOwnerRequest request) {
            return base.Channel.SetScriptOwner(request);
        }
        
        public void SetScriptOwner(string scriptName, int userId) {
            PTZCameraTester.ScriptControl.SetScriptOwnerRequest inValue = new PTZCameraTester.ScriptControl.SetScriptOwnerRequest();
            inValue.scriptName = scriptName;
            inValue.userId = userId;
            PTZCameraTester.ScriptControl.SetScriptOwnerResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).SetScriptOwner(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.ScriptControl.QueryActionsResponse PTZCameraTester.ScriptControl.ScriptControlPortType.QueryActions(PTZCameraTester.ScriptControl.QueryActionsRequest request) {
            return base.Channel.QueryActions(request);
        }
        
        public void QueryActions(ref PTZCameraTester.ScriptControl.ScriptActionList scriptActionList) {
            PTZCameraTester.ScriptControl.QueryActionsRequest inValue = new PTZCameraTester.ScriptControl.QueryActionsRequest();
            inValue.scriptActionList = scriptActionList;
            PTZCameraTester.ScriptControl.QueryActionsResponse retVal = ((PTZCameraTester.ScriptControl.ScriptControlPortType)(this)).QueryActions(inValue);
            scriptActionList = retVal.scriptActionList;
        }
    }
}
