//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZCameraTester.AlarmArrayConfiguration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", ConfigurationName="AlarmArrayConfiguration.AlarmArrayConfigurationPortType")]
    public interface AlarmArrayConfigurationPortType {
        
        // CODEGEN: Parameter 'alarmStates' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#GetAlarmStates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="alarmStates")]
        PTZCameraTester.AlarmArrayConfiguration.GetAlarmStatesResponse GetAlarmStates(PTZCameraTester.AlarmArrayConfiguration.GetAlarmStatesRequest request);
        
        // CODEGEN: Parameter 'size' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#GetArraySize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="size")]
        PTZCameraTester.AlarmArrayConfiguration.GetArraySizeResponse GetArraySize(PTZCameraTester.AlarmArrayConfiguration.GetArraySizeRequest request);
        
        // CODEGEN: Parameter 'alarmID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#SetAlarmState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.AlarmArrayConfiguration.SetAlarmStateResponse SetAlarmState(PTZCameraTester.AlarmArrayConfiguration.SetAlarmStateRequest request);
        
        // CODEGEN: Parameter 'alarmConfig' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#GetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="alarmConfig")]
        PTZCameraTester.AlarmArrayConfiguration.GetConfigurationResponse GetConfiguration(PTZCameraTester.AlarmArrayConfiguration.GetConfigurationRequest request);
        
        // CODEGEN: Parameter 'alarmID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#SetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.AlarmArrayConfiguration.SetConfigurationResponse SetConfiguration(PTZCameraTester.AlarmArrayConfiguration.SetConfigurationRequest request);
        
        // CODEGEN: Parameter 'alarmID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1#ResetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.AlarmArrayConfiguration.ResetConfigurationResponse ResetConfiguration(PTZCameraTester.AlarmArrayConfiguration.ResetConfigurationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1")]
    public partial class AlarmStates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int objIdField;
        
        private bool objIdFieldSpecified;
        
        private int offsetField;
        
        private bool offsetFieldSpecified;
        
        private int lengthField;
        
        private string changedField;
        
        private string state1Field;
        
        private string state2Field;
        
        private string enabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int objId {
            get {
                return this.objIdField;
            }
            set {
                this.objIdField = value;
                this.RaisePropertyChanged("objId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objIdSpecified {
            get {
                return this.objIdFieldSpecified;
            }
            set {
                this.objIdFieldSpecified = value;
                this.RaisePropertyChanged("objIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
                this.RaisePropertyChanged("offsetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
                this.RaisePropertyChanged("changed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string state1 {
            get {
                return this.state1Field;
            }
            set {
                this.state1Field = value;
                this.RaisePropertyChanged("state1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string state2 {
            get {
                return this.state2Field;
            }
            set {
                this.state2Field = value;
                this.RaisePropertyChanged("state2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("enabled");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1")]
    public partial class PROPERTY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private string comparatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comparator {
            get {
                return this.comparatorField;
            }
            set {
                this.comparatorField = value;
                this.RaisePropertyChanged("comparator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1")]
    public partial class EVENT_ENTRY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uidField;
        
        private string eventURIField;
        
        private string eventTypeField;
        
        private string serviceTypeField;
        
        private PROPERTY[] propertySetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string eventURI {
            get {
                return this.eventURIField;
            }
            set {
                this.eventURIField = value;
                this.RaisePropertyChanged("eventURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("eventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PROPERTY[] propertySet {
            get {
                return this.propertySetField;
            }
            set {
                this.propertySetField = value;
                this.RaisePropertyChanged("propertySet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1")]
    public partial class OPSTACK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string operatorField;
        
        private EVENT_ENTRY[] event_entriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eventEntry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EVENT_ENTRY[] event_entries {
            get {
                return this.event_entriesField;
            }
            set {
                this.event_entriesField = value;
                this.RaisePropertyChanged("event_entries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1")]
    public partial class COMBINED_EVENT_ENTRY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OPSTACK opStackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OPSTACK opStack {
            get {
                return this.opStackField;
            }
            set {
                this.opStackField = value;
                this.RaisePropertyChanged("opStack");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1")]
    public partial class AlarmConfig : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int severityField;
        
        private bool severityFieldSpecified;
        
        private int polarityField;
        
        private int enabledField;
        
        private int supervisedField;
        
        private double dwellTimeField;
        
        private int physicalInputField;
        
        private COMBINED_EVENT_ENTRY combinedEventEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
                this.RaisePropertyChanged("severitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int polarity {
            get {
                return this.polarityField;
            }
            set {
                this.polarityField = value;
                this.RaisePropertyChanged("polarity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int supervised {
            get {
                return this.supervisedField;
            }
            set {
                this.supervisedField = value;
                this.RaisePropertyChanged("supervised");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double dwellTime {
            get {
                return this.dwellTimeField;
            }
            set {
                this.dwellTimeField = value;
                this.RaisePropertyChanged("dwellTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int physicalInput {
            get {
                return this.physicalInputField;
            }
            set {
                this.physicalInputField = value;
                this.RaisePropertyChanged("physicalInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public COMBINED_EVENT_ENTRY combinedEventEntry {
            get {
                return this.combinedEventEntryField;
            }
            set {
                this.combinedEventEntryField = value;
                this.RaisePropertyChanged("combinedEventEntry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlarmStates", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class GetAlarmStatesRequest {
        
        public GetAlarmStatesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlarmStatesResponse", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class GetAlarmStatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AlarmArrayConfiguration.AlarmStates alarmStates;
        
        public GetAlarmStatesResponse() {
        }
        
        public GetAlarmStatesResponse(PTZCameraTester.AlarmArrayConfiguration.AlarmStates alarmStates) {
            this.alarmStates = alarmStates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArraySize", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class GetArraySizeRequest {
        
        public GetArraySizeRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArraySizeResponse", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class GetArraySizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int size;
        
        public GetArraySizeResponse() {
        }
        
        public GetArraySizeResponse(int size) {
            this.size = size;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAlarmState", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class SetAlarmStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int alarmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int alarmState;
        
        public SetAlarmStateRequest() {
        }
        
        public SetAlarmStateRequest(int alarmID, int alarmState) {
            this.alarmID = alarmID;
            this.alarmState = alarmState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAlarmStateResponse", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class SetAlarmStateResponse {
        
        public SetAlarmStateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class GetConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int alarmID;
        
        public GetConfigurationRequest() {
        }
        
        public GetConfigurationRequest(int alarmID) {
            this.alarmID = alarmID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class GetConfigurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AlarmArrayConfiguration.AlarmConfig alarmConfig;
        
        public GetConfigurationResponse() {
        }
        
        public GetConfigurationResponse(PTZCameraTester.AlarmArrayConfiguration.AlarmConfig alarmConfig) {
            this.alarmConfig = alarmConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class SetConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int alarmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AlarmArrayConfiguration.AlarmConfig alarmConfig;
        
        public SetConfigurationRequest() {
        }
        
        public SetConfigurationRequest(int alarmID, PTZCameraTester.AlarmArrayConfiguration.AlarmConfig alarmConfig) {
            this.alarmID = alarmID;
            this.alarmConfig = alarmConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class SetConfigurationResponse {
        
        public SetConfigurationResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class ResetConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int alarmID;
        
        public ResetConfigurationRequest() {
        }
        
        public ResetConfigurationRequest(int alarmID) {
            this.alarmID = alarmID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:AlarmArrayConfiguration:1", IsWrapped=true)]
    public partial class ResetConfigurationResponse {
        
        public ResetConfigurationResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlarmArrayConfigurationPortTypeChannel : PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmArrayConfigurationPortTypeClient : System.ServiceModel.ClientBase<PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType>, PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType {
        
        public AlarmArrayConfigurationPortTypeClient() {
        }
        
        public AlarmArrayConfigurationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlarmArrayConfigurationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmArrayConfigurationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmArrayConfigurationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AlarmArrayConfiguration.GetAlarmStatesResponse PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType.GetAlarmStates(PTZCameraTester.AlarmArrayConfiguration.GetAlarmStatesRequest request) {
            return base.Channel.GetAlarmStates(request);
        }
        
        public PTZCameraTester.AlarmArrayConfiguration.AlarmStates GetAlarmStates() {
            PTZCameraTester.AlarmArrayConfiguration.GetAlarmStatesRequest inValue = new PTZCameraTester.AlarmArrayConfiguration.GetAlarmStatesRequest();
            PTZCameraTester.AlarmArrayConfiguration.GetAlarmStatesResponse retVal = ((PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType)(this)).GetAlarmStates(inValue);
            return retVal.alarmStates;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AlarmArrayConfiguration.GetArraySizeResponse PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType.GetArraySize(PTZCameraTester.AlarmArrayConfiguration.GetArraySizeRequest request) {
            return base.Channel.GetArraySize(request);
        }
        
        public int GetArraySize() {
            PTZCameraTester.AlarmArrayConfiguration.GetArraySizeRequest inValue = new PTZCameraTester.AlarmArrayConfiguration.GetArraySizeRequest();
            PTZCameraTester.AlarmArrayConfiguration.GetArraySizeResponse retVal = ((PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType)(this)).GetArraySize(inValue);
            return retVal.size;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AlarmArrayConfiguration.SetAlarmStateResponse PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType.SetAlarmState(PTZCameraTester.AlarmArrayConfiguration.SetAlarmStateRequest request) {
            return base.Channel.SetAlarmState(request);
        }
        
        public void SetAlarmState(int alarmID, int alarmState) {
            PTZCameraTester.AlarmArrayConfiguration.SetAlarmStateRequest inValue = new PTZCameraTester.AlarmArrayConfiguration.SetAlarmStateRequest();
            inValue.alarmID = alarmID;
            inValue.alarmState = alarmState;
            PTZCameraTester.AlarmArrayConfiguration.SetAlarmStateResponse retVal = ((PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType)(this)).SetAlarmState(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AlarmArrayConfiguration.GetConfigurationResponse PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType.GetConfiguration(PTZCameraTester.AlarmArrayConfiguration.GetConfigurationRequest request) {
            return base.Channel.GetConfiguration(request);
        }
        
        public PTZCameraTester.AlarmArrayConfiguration.AlarmConfig GetConfiguration(int alarmID) {
            PTZCameraTester.AlarmArrayConfiguration.GetConfigurationRequest inValue = new PTZCameraTester.AlarmArrayConfiguration.GetConfigurationRequest();
            inValue.alarmID = alarmID;
            PTZCameraTester.AlarmArrayConfiguration.GetConfigurationResponse retVal = ((PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType)(this)).GetConfiguration(inValue);
            return retVal.alarmConfig;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AlarmArrayConfiguration.SetConfigurationResponse PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType.SetConfiguration(PTZCameraTester.AlarmArrayConfiguration.SetConfigurationRequest request) {
            return base.Channel.SetConfiguration(request);
        }
        
        public void SetConfiguration(int alarmID, PTZCameraTester.AlarmArrayConfiguration.AlarmConfig alarmConfig) {
            PTZCameraTester.AlarmArrayConfiguration.SetConfigurationRequest inValue = new PTZCameraTester.AlarmArrayConfiguration.SetConfigurationRequest();
            inValue.alarmID = alarmID;
            inValue.alarmConfig = alarmConfig;
            PTZCameraTester.AlarmArrayConfiguration.SetConfigurationResponse retVal = ((PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType)(this)).SetConfiguration(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AlarmArrayConfiguration.ResetConfigurationResponse PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType.ResetConfiguration(PTZCameraTester.AlarmArrayConfiguration.ResetConfigurationRequest request) {
            return base.Channel.ResetConfiguration(request);
        }
        
        public void ResetConfiguration(int alarmID) {
            PTZCameraTester.AlarmArrayConfiguration.ResetConfigurationRequest inValue = new PTZCameraTester.AlarmArrayConfiguration.ResetConfigurationRequest();
            inValue.alarmID = alarmID;
            PTZCameraTester.AlarmArrayConfiguration.ResetConfigurationResponse retVal = ((PTZCameraTester.AlarmArrayConfiguration.AlarmArrayConfigurationPortType)(this)).ResetConfiguration(inValue);
        }
    }
}
