//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZCameraTester.StreamConfiguration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", ConfigurationName="StreamConfiguration.StreamConfigurationPortType")]
    public interface StreamConfigurationPortType {
        
        // CODEGEN: Parameter 'streamCount' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#GetStreamCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="streamCount")]
        PTZCameraTester.StreamConfiguration.GetStreamCountResponse GetStreamCount(PTZCameraTester.StreamConfiguration.GetStreamCountRequest request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#GetCurrentConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        PTZCameraTester.StreamConfiguration.GetCurrentConfigurationResponse GetCurrentConfiguration(PTZCameraTester.StreamConfiguration.GetCurrentConfigurationRequest request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#QueryOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        PTZCameraTester.StreamConfiguration.QueryOptionsResponse QueryOptions(PTZCameraTester.StreamConfiguration.QueryOptionsRequest request);
        
        // CODEGEN: Parameter 'stream' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#SaveSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.StreamConfiguration.SaveSettingsResponse SaveSettings(PTZCameraTester.StreamConfiguration.SaveSettingsRequest request);
        
        // CODEGEN: Parameter 'streamSettingsList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#GetAllSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="streamSettingsList")]
        PTZCameraTester.StreamConfiguration.GetAllSettingsResponse GetAllSettings(PTZCameraTester.StreamConfiguration.GetAllSettingsRequest request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#GetAllCurrentConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        PTZCameraTester.StreamConfiguration.GetAllCurrentConfigurationResponse GetAllCurrentConfiguration(PTZCameraTester.StreamConfiguration.GetAllCurrentConfigurationRequest request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#QueryAllOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        PTZCameraTester.StreamConfiguration.QueryAllOptionsResponse QueryAllOptions(PTZCameraTester.StreamConfiguration.QueryAllOptionsRequest request);
        
        // CODEGEN: Parameter 'streamType' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#SaveAllSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.StreamConfiguration.SaveAllSettingsResponse SaveAllSettings(PTZCameraTester.StreamConfiguration.SaveAllSettingsRequest request);
        
        // CODEGEN: Parameter 'streamType' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#ApplyDynamicSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.StreamConfiguration.ApplyDynamicSettingsResponse ApplyDynamicSettings(PTZCameraTester.StreamConfiguration.ApplyDynamicSettingsRequest request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#GetPresets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        PTZCameraTester.StreamConfiguration.GetPresetsResponse GetPresets(PTZCameraTester.StreamConfiguration.GetPresetsRequest request);
        
        // CODEGEN: Parameter 'presetName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:StreamConfiguration:1#GetCurrentPresetName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="presetName")]
        PTZCameraTester.StreamConfiguration.GetCurrentPresetNameResponse GetCurrentPresetName(PTZCameraTester.StreamConfiguration.GetCurrentPresetNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStreamCount", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetStreamCountRequest {
        
        public GetStreamCountRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStreamCountResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetStreamCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int streamCount;
        
        public GetStreamCountResponse() {
        }
        
        public GetStreamCountResponse(int streamCount) {
            this.streamCount = streamCount;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class StreamID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class Preset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptiveNameField;
        
        private bool validField;
        
        private StreamIDSettings[] streamSettingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descriptiveName {
            get {
                return this.descriptiveNameField;
            }
            set {
                this.descriptiveNameField = value;
                this.RaisePropertyChanged("descriptiveName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("streamIDSettings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StreamIDSettings[] streamSettings {
            get {
                return this.streamSettingsField;
            }
            set {
                this.streamSettingsField = value;
                this.RaisePropertyChanged("streamSettings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class StreamIDSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StreamID streamField;
        
        private Setting[] settingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StreamID stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
                this.RaisePropertyChanged("stream");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("setting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Setting[] settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
                this.RaisePropertyChanged("settings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class Setting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("booleanValue", typeof(bool), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("decimalValue", typeof(decimal), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("intValue", typeof(int), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("resolutionValue", typeof(Resolution), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("stringValue", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class Resolution : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class StreamConfigurationInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StreamID streamField;
        
        private QueryResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StreamID stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
                this.RaisePropertyChanged("stream");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public QueryResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class QueryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Setting[] settingField;
        
        private SettingOptions[] settingOptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("setting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Setting[] setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
                this.RaisePropertyChanged("setting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("settingOptions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SettingOptions[] settingOptions {
            get {
                return this.settingOptionsField;
            }
            set {
                this.settingOptionsField = value;
                this.RaisePropertyChanged("settingOptions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class SettingOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boolean", typeof(BooleanOption), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("decimalEnumeration", typeof(DecimalEnumeration), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("freeFormString", typeof(FreeFormString), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("intRange", typeof(IntRange), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("resolutionEnumeration", typeof(ResolutionEnumeration), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("stringEnumeration", typeof(StringEnumeration), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class BooleanOption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool defaultField;
        
        private bool defaultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
                this.RaisePropertyChanged("default");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultSpecified {
            get {
                return this.defaultFieldSpecified;
            }
            set {
                this.defaultFieldSpecified = value;
                this.RaisePropertyChanged("defaultSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class DecimalEnumeration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class FreeFormString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int maxLengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int maxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
                this.RaisePropertyChanged("maxLength");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class IntRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int minValueField;
        
        private int maxValueField;
        
        private int defaultField;
        
        private bool defaultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int minValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
                this.RaisePropertyChanged("minValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int maxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
                this.RaisePropertyChanged("maxValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
                this.RaisePropertyChanged("default");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultSpecified {
            get {
                return this.defaultFieldSpecified;
            }
            set {
                this.defaultFieldSpecified = value;
                this.RaisePropertyChanged("defaultSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class ResolutionEnumeration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Resolution[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Resolution[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class StringEnumeration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class ResourceUtilization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resourceField;
        
        private int utilizationPctField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
                this.RaisePropertyChanged("resource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int utilizationPct {
            get {
                return this.utilizationPctField;
            }
            set {
                this.utilizationPctField = value;
                this.RaisePropertyChanged("utilizationPct");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1")]
    public partial class ConfigurationInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResourceUtilization[] resourceUtilizationField;
        
        private StreamConfigurationInfo[] streamInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resourceUtilization", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResourceUtilization[] resourceUtilization {
            get {
                return this.resourceUtilizationField;
            }
            set {
                this.resourceUtilizationField = value;
                this.RaisePropertyChanged("resourceUtilization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("streamInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StreamConfigurationInfo[] streamInfo {
            get {
                return this.streamInfoField;
            }
            set {
                this.streamInfoField = value;
                this.RaisePropertyChanged("streamInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetCurrentConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.StreamConfiguration.StreamID stream;
        
        public GetCurrentConfigurationRequest() {
        }
        
        public GetCurrentConfigurationRequest(PTZCameraTester.StreamConfiguration.StreamID stream) {
            this.stream = stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetCurrentConfigurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.StreamConfiguration.QueryResult result;
        
        public GetCurrentConfigurationResponse() {
        }
        
        public GetCurrentConfigurationResponse(PTZCameraTester.StreamConfiguration.QueryResult result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryOptions", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class QueryOptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.StreamConfiguration.StreamID stream;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("setting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PTZCameraTester.StreamConfiguration.Setting[] filter;
        
        public QueryOptionsRequest() {
        }
        
        public QueryOptionsRequest(PTZCameraTester.StreamConfiguration.StreamID stream, PTZCameraTester.StreamConfiguration.Setting[] filter) {
            this.stream = stream;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryOptionsResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class QueryOptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.StreamConfiguration.QueryResult result;
        
        public QueryOptionsResponse() {
        }
        
        public QueryOptionsResponse(PTZCameraTester.StreamConfiguration.QueryResult result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveSettings", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class SaveSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.StreamConfiguration.StreamID stream;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("setting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PTZCameraTester.StreamConfiguration.Setting[] settings;
        
        public SaveSettingsRequest() {
        }
        
        public SaveSettingsRequest(PTZCameraTester.StreamConfiguration.StreamID stream, PTZCameraTester.StreamConfiguration.Setting[] settings) {
            this.stream = stream;
            this.settings = settings;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveSettingsResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class SaveSettingsResponse {
        
        public SaveSettingsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSettings", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetAllSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streamType;
        
        public GetAllSettingsRequest() {
        }
        
        public GetAllSettingsRequest(string streamType) {
            this.streamType = streamType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSettingsResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetAllSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("streamIDSettings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList;
        
        public GetAllSettingsResponse() {
        }
        
        public GetAllSettingsResponse(PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList) {
            this.streamSettingsList = streamSettingsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCurrentConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetAllCurrentConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streamType;
        
        public GetAllCurrentConfigurationRequest() {
        }
        
        public GetAllCurrentConfigurationRequest(string streamType) {
            this.streamType = streamType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCurrentConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetAllCurrentConfigurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.StreamConfiguration.ConfigurationInfo result;
        
        public GetAllCurrentConfigurationResponse() {
        }
        
        public GetAllCurrentConfigurationResponse(PTZCameraTester.StreamConfiguration.ConfigurationInfo result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllOptions", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class QueryAllOptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streamType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("streamIDSettings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList;
        
        public QueryAllOptionsRequest() {
        }
        
        public QueryAllOptionsRequest(string streamType, PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList) {
            this.streamType = streamType;
            this.streamSettingsList = streamSettingsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryAllOptionsResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class QueryAllOptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.StreamConfiguration.ConfigurationInfo result;
        
        public QueryAllOptionsResponse() {
        }
        
        public QueryAllOptionsResponse(PTZCameraTester.StreamConfiguration.ConfigurationInfo result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAllSettings", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class SaveAllSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streamType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("streamIDSettings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList;
        
        public SaveAllSettingsRequest() {
        }
        
        public SaveAllSettingsRequest(string streamType, PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList) {
            this.streamType = streamType;
            this.streamSettingsList = streamSettingsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAllSettingsResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class SaveAllSettingsResponse {
        
        public SaveAllSettingsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyDynamicSettings", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class ApplyDynamicSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string streamType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("streamIDSettings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList;
        
        public ApplyDynamicSettingsRequest() {
        }
        
        public ApplyDynamicSettingsRequest(string streamType, PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList) {
            this.streamType = streamType;
            this.streamSettingsList = streamSettingsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyDynamicSettingsResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class ApplyDynamicSettingsResponse {
        
        public ApplyDynamicSettingsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresets", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetPresetsRequest {
        
        public GetPresetsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetsResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetPresetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("preset", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PTZCameraTester.StreamConfiguration.Preset[] result;
        
        public GetPresetsResponse() {
        }
        
        public GetPresetsResponse(PTZCameraTester.StreamConfiguration.Preset[] result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentPresetName", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetCurrentPresetNameRequest {
        
        public GetCurrentPresetNameRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentPresetNameResponse", WrapperNamespace="urn:schemas-pelco-com:service:StreamConfiguration:1", IsWrapped=true)]
    public partial class GetCurrentPresetNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:StreamConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string presetName;
        
        public GetCurrentPresetNameResponse() {
        }
        
        public GetCurrentPresetNameResponse(string presetName) {
            this.presetName = presetName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StreamConfigurationPortTypeChannel : PTZCameraTester.StreamConfiguration.StreamConfigurationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamConfigurationPortTypeClient : System.ServiceModel.ClientBase<PTZCameraTester.StreamConfiguration.StreamConfigurationPortType>, PTZCameraTester.StreamConfiguration.StreamConfigurationPortType {
        
        public StreamConfigurationPortTypeClient() {
        }
        
        public StreamConfigurationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamConfigurationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamConfigurationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamConfigurationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.GetStreamCountResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.GetStreamCount(PTZCameraTester.StreamConfiguration.GetStreamCountRequest request) {
            return base.Channel.GetStreamCount(request);
        }
        
        public int GetStreamCount() {
            PTZCameraTester.StreamConfiguration.GetStreamCountRequest inValue = new PTZCameraTester.StreamConfiguration.GetStreamCountRequest();
            PTZCameraTester.StreamConfiguration.GetStreamCountResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).GetStreamCount(inValue);
            return retVal.streamCount;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.GetCurrentConfigurationResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.GetCurrentConfiguration(PTZCameraTester.StreamConfiguration.GetCurrentConfigurationRequest request) {
            return base.Channel.GetCurrentConfiguration(request);
        }
        
        public PTZCameraTester.StreamConfiguration.QueryResult GetCurrentConfiguration(PTZCameraTester.StreamConfiguration.StreamID stream) {
            PTZCameraTester.StreamConfiguration.GetCurrentConfigurationRequest inValue = new PTZCameraTester.StreamConfiguration.GetCurrentConfigurationRequest();
            inValue.stream = stream;
            PTZCameraTester.StreamConfiguration.GetCurrentConfigurationResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).GetCurrentConfiguration(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.QueryOptionsResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.QueryOptions(PTZCameraTester.StreamConfiguration.QueryOptionsRequest request) {
            return base.Channel.QueryOptions(request);
        }
        
        public PTZCameraTester.StreamConfiguration.QueryResult QueryOptions(PTZCameraTester.StreamConfiguration.StreamID stream, PTZCameraTester.StreamConfiguration.Setting[] filter) {
            PTZCameraTester.StreamConfiguration.QueryOptionsRequest inValue = new PTZCameraTester.StreamConfiguration.QueryOptionsRequest();
            inValue.stream = stream;
            inValue.filter = filter;
            PTZCameraTester.StreamConfiguration.QueryOptionsResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).QueryOptions(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.SaveSettingsResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.SaveSettings(PTZCameraTester.StreamConfiguration.SaveSettingsRequest request) {
            return base.Channel.SaveSettings(request);
        }
        
        public void SaveSettings(PTZCameraTester.StreamConfiguration.StreamID stream, PTZCameraTester.StreamConfiguration.Setting[] settings) {
            PTZCameraTester.StreamConfiguration.SaveSettingsRequest inValue = new PTZCameraTester.StreamConfiguration.SaveSettingsRequest();
            inValue.stream = stream;
            inValue.settings = settings;
            PTZCameraTester.StreamConfiguration.SaveSettingsResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).SaveSettings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.GetAllSettingsResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.GetAllSettings(PTZCameraTester.StreamConfiguration.GetAllSettingsRequest request) {
            return base.Channel.GetAllSettings(request);
        }
        
        public PTZCameraTester.StreamConfiguration.StreamIDSettings[] GetAllSettings(string streamType) {
            PTZCameraTester.StreamConfiguration.GetAllSettingsRequest inValue = new PTZCameraTester.StreamConfiguration.GetAllSettingsRequest();
            inValue.streamType = streamType;
            PTZCameraTester.StreamConfiguration.GetAllSettingsResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).GetAllSettings(inValue);
            return retVal.streamSettingsList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.GetAllCurrentConfigurationResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.GetAllCurrentConfiguration(PTZCameraTester.StreamConfiguration.GetAllCurrentConfigurationRequest request) {
            return base.Channel.GetAllCurrentConfiguration(request);
        }
        
        public PTZCameraTester.StreamConfiguration.ConfigurationInfo GetAllCurrentConfiguration(string streamType) {
            PTZCameraTester.StreamConfiguration.GetAllCurrentConfigurationRequest inValue = new PTZCameraTester.StreamConfiguration.GetAllCurrentConfigurationRequest();
            inValue.streamType = streamType;
            PTZCameraTester.StreamConfiguration.GetAllCurrentConfigurationResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).GetAllCurrentConfiguration(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.QueryAllOptionsResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.QueryAllOptions(PTZCameraTester.StreamConfiguration.QueryAllOptionsRequest request) {
            return base.Channel.QueryAllOptions(request);
        }
        
        public PTZCameraTester.StreamConfiguration.ConfigurationInfo QueryAllOptions(string streamType, PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList) {
            PTZCameraTester.StreamConfiguration.QueryAllOptionsRequest inValue = new PTZCameraTester.StreamConfiguration.QueryAllOptionsRequest();
            inValue.streamType = streamType;
            inValue.streamSettingsList = streamSettingsList;
            PTZCameraTester.StreamConfiguration.QueryAllOptionsResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).QueryAllOptions(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.SaveAllSettingsResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.SaveAllSettings(PTZCameraTester.StreamConfiguration.SaveAllSettingsRequest request) {
            return base.Channel.SaveAllSettings(request);
        }
        
        public void SaveAllSettings(string streamType, PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList) {
            PTZCameraTester.StreamConfiguration.SaveAllSettingsRequest inValue = new PTZCameraTester.StreamConfiguration.SaveAllSettingsRequest();
            inValue.streamType = streamType;
            inValue.streamSettingsList = streamSettingsList;
            PTZCameraTester.StreamConfiguration.SaveAllSettingsResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).SaveAllSettings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.ApplyDynamicSettingsResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.ApplyDynamicSettings(PTZCameraTester.StreamConfiguration.ApplyDynamicSettingsRequest request) {
            return base.Channel.ApplyDynamicSettings(request);
        }
        
        public void ApplyDynamicSettings(string streamType, PTZCameraTester.StreamConfiguration.StreamIDSettings[] streamSettingsList) {
            PTZCameraTester.StreamConfiguration.ApplyDynamicSettingsRequest inValue = new PTZCameraTester.StreamConfiguration.ApplyDynamicSettingsRequest();
            inValue.streamType = streamType;
            inValue.streamSettingsList = streamSettingsList;
            PTZCameraTester.StreamConfiguration.ApplyDynamicSettingsResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).ApplyDynamicSettings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.GetPresetsResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.GetPresets(PTZCameraTester.StreamConfiguration.GetPresetsRequest request) {
            return base.Channel.GetPresets(request);
        }
        
        public PTZCameraTester.StreamConfiguration.Preset[] GetPresets() {
            PTZCameraTester.StreamConfiguration.GetPresetsRequest inValue = new PTZCameraTester.StreamConfiguration.GetPresetsRequest();
            PTZCameraTester.StreamConfiguration.GetPresetsResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).GetPresets(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.StreamConfiguration.GetCurrentPresetNameResponse PTZCameraTester.StreamConfiguration.StreamConfigurationPortType.GetCurrentPresetName(PTZCameraTester.StreamConfiguration.GetCurrentPresetNameRequest request) {
            return base.Channel.GetCurrentPresetName(request);
        }
        
        public string GetCurrentPresetName() {
            PTZCameraTester.StreamConfiguration.GetCurrentPresetNameRequest inValue = new PTZCameraTester.StreamConfiguration.GetCurrentPresetNameRequest();
            PTZCameraTester.StreamConfiguration.GetCurrentPresetNameResponse retVal = ((PTZCameraTester.StreamConfiguration.StreamConfigurationPortType)(this)).GetCurrentPresetName(inValue);
            return retVal.presetName;
        }
    }
}
