//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZCameraTester.PresetControl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", ConfigurationName="PresetControl.PresetControlPortType")]
    public interface PresetControlPortType {
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#ForceSetPreset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="id")]
        PTZCameraTester.PresetControl.ForceSetPresetResponse ForceSetPreset(PTZCameraTester.PresetControl.ForceSetPresetRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#SetPreset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="id")]
        PTZCameraTester.PresetControl.SetPresetResponse SetPreset(PTZCameraTester.PresetControl.SetPresetRequest request);
        
        // CODEGEN: Parameter 'presetList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetPresets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="presetList")]
        PTZCameraTester.PresetControl.GetPresetsResponse GetPresets(PTZCameraTester.PresetControl.GetPresetsRequest request);
        
        // CODEGEN: Parameter 'idList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetPresetIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="idList")]
        PTZCameraTester.PresetControl.GetPresetIdsResponse GetPresetIds(PTZCameraTester.PresetControl.GetPresetIdsRequest request);
        
        // CODEGEN: Parameter 'nameList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetPresetNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="nameList")]
        PTZCameraTester.PresetControl.GetPresetNamesResponse GetPresetNames(PTZCameraTester.PresetControl.GetPresetNamesRequest request);
        
        // CODEGEN: Parameter 'maxPresets' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetMaxPresets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="maxPresets")]
        PTZCameraTester.PresetControl.GetMaxPresetsResponse GetMaxPresets(PTZCameraTester.PresetControl.GetMaxPresetsRequest request);
        
        // CODEGEN: Parameter 'idList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#ForceRemovePresets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.PresetControl.ForceRemovePresetsResponse ForceRemovePresets(PTZCameraTester.PresetControl.ForceRemovePresetsRequest request);
        
        // CODEGEN: Parameter 'idList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#RemovePresets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.PresetControl.RemovePresetsResponse RemovePresets(PTZCameraTester.PresetControl.RemovePresetsRequest request);
        
        // CODEGEN: Parameter 'move' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GotoPreset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.PresetControl.GotoPresetResponse GotoPreset(PTZCameraTester.PresetControl.GotoPresetRequest request);
        
        // CODEGEN: Parameter 'pathList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GenerateThumbnails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pathList")]
        PTZCameraTester.PresetControl.GenerateThumbnailsResponse GenerateThumbnails(PTZCameraTester.PresetControl.GenerateThumbnailsRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#SetTour", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="id")]
        PTZCameraTester.PresetControl.SetTourResponse SetTour(PTZCameraTester.PresetControl.SetTourRequest request);
        
        // CODEGEN: Parameter 'tourList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetTours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tourList")]
        PTZCameraTester.PresetControl.GetToursResponse GetTours(PTZCameraTester.PresetControl.GetToursRequest request);
        
        // CODEGEN: Parameter 'idList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetTourIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="idList")]
        PTZCameraTester.PresetControl.GetTourIdsResponse GetTourIds(PTZCameraTester.PresetControl.GetTourIdsRequest request);
        
        // CODEGEN: Parameter 'nameList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetTourNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="nameList")]
        PTZCameraTester.PresetControl.GetTourNamesResponse GetTourNames(PTZCameraTester.PresetControl.GetTourNamesRequest request);
        
        // CODEGEN: Parameter 'maxTours' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetMaxTours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="maxTours")]
        PTZCameraTester.PresetControl.GetMaxToursResponse GetMaxTours(PTZCameraTester.PresetControl.GetMaxToursRequest request);
        
        // CODEGEN: Parameter 'maxPresetsPerTour' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#GetMaxPresetsPerTour", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="maxPresetsPerTour")]
        PTZCameraTester.PresetControl.GetMaxPresetsPerTourResponse GetMaxPresetsPerTour(PTZCameraTester.PresetControl.GetMaxPresetsPerTourRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#StopTour", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StopTour();
        
        // CODEGEN: Parameter 'idList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#RemoveTours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.PresetControl.RemoveToursResponse RemoveTours(PTZCameraTester.PresetControl.RemoveToursRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PresetControl:2#StartTour", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.PresetControl.StartTourResponse StartTour(PTZCameraTester.PresetControl.StartTourRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class SetPreset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private bool autoFocusField;
        
        private bool autoFocusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool autoFocus {
            get {
                return this.autoFocusField;
            }
            set {
                this.autoFocusField = value;
                this.RaisePropertyChanged("autoFocus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoFocusSpecified {
            get {
                return this.autoFocusFieldSpecified;
            }
            set {
                this.autoFocusFieldSpecified = value;
                this.RaisePropertyChanged("autoFocusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class Stop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Preset presetField;
        
        private int dwellTimeSecondsField;
        
        private float transitionSpeedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Preset preset {
            get {
                return this.presetField;
            }
            set {
                this.presetField = value;
                this.RaisePropertyChanged("preset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dwellTimeSeconds {
            get {
                return this.dwellTimeSecondsField;
            }
            set {
                this.dwellTimeSecondsField = value;
                this.RaisePropertyChanged("dwellTimeSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float transitionSpeed {
            get {
                return this.transitionSpeedField;
            }
            set {
                this.transitionSpeedField = value;
                this.RaisePropertyChanged("transitionSpeed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class Preset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private bool autoFocusField;
        
        private bool hasThumbnailField;
        
        private string thumbnailPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool autoFocus {
            get {
                return this.autoFocusField;
            }
            set {
                this.autoFocusField = value;
                this.RaisePropertyChanged("autoFocus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool hasThumbnail {
            get {
                return this.hasThumbnailField;
            }
            set {
                this.hasThumbnailField = value;
                this.RaisePropertyChanged("hasThumbnail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string thumbnailPath {
            get {
                return this.thumbnailPathField;
            }
            set {
                this.thumbnailPathField = value;
                this.RaisePropertyChanged("thumbnailPath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class Tour : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private Stop[] stopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stop", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Stop[] stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
                this.RaisePropertyChanged("stop");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class SetStop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string presetField;
        
        private int dwellTimeSecondsField;
        
        private float transitionSpeedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string preset {
            get {
                return this.presetField;
            }
            set {
                this.presetField = value;
                this.RaisePropertyChanged("preset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dwellTimeSeconds {
            get {
                return this.dwellTimeSecondsField;
            }
            set {
                this.dwellTimeSecondsField = value;
                this.RaisePropertyChanged("dwellTimeSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float transitionSpeed {
            get {
                return this.transitionSpeedField;
            }
            set {
                this.transitionSpeedField = value;
                this.RaisePropertyChanged("transitionSpeed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class SetTour : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private SetStop[] stopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stop", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SetStop[] stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
                this.RaisePropertyChanged("stop");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class GotoPreset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private float transitionSpeedField;
        
        private bool transitionSpeedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float transitionSpeed {
            get {
                return this.transitionSpeedField;
            }
            set {
                this.transitionSpeedField = value;
                this.RaisePropertyChanged("transitionSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transitionSpeedSpecified {
            get {
                return this.transitionSpeedFieldSpecified;
            }
            set {
                this.transitionSpeedFieldSpecified = value;
                this.RaisePropertyChanged("transitionSpeedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2")]
    public partial class Name : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceSetPreset", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class ForceSetPresetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.PresetControl.SetPreset preset;
        
        public ForceSetPresetRequest() {
        }
        
        public ForceSetPresetRequest(PTZCameraTester.PresetControl.SetPreset preset) {
            this.preset = preset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceSetPresetResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class ForceSetPresetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public ForceSetPresetResponse() {
        }
        
        public ForceSetPresetResponse(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPreset", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class SetPresetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.PresetControl.SetPreset preset;
        
        public SetPresetRequest() {
        }
        
        public SetPresetRequest(PTZCameraTester.PresetControl.SetPreset preset) {
            this.preset = preset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPresetResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class SetPresetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public SetPresetResponse() {
        }
        
        public SetPresetResponse(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresets", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetPresetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public GetPresetsRequest() {
        }
        
        public GetPresetsRequest(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetsResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetPresetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("preset", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Preset[] presetList;
        
        public GetPresetsResponse() {
        }
        
        public GetPresetsResponse(Preset[] presetList) {
            this.presetList = presetList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetIds", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetPresetIdsRequest {
        
        public GetPresetIdsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetIdsResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetPresetIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public GetPresetIdsResponse() {
        }
        
        public GetPresetIdsResponse(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetNames", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetPresetNamesRequest {
        
        public GetPresetNamesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPresetNamesResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetPresetNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Name[] nameList;
        
        public GetPresetNamesResponse() {
        }
        
        public GetPresetNamesResponse(Name[] nameList) {
            this.nameList = nameList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaxPresets", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetMaxPresetsRequest {
        
        public GetMaxPresetsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaxPresetsResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetMaxPresetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxPresets;
        
        public GetMaxPresetsResponse() {
        }
        
        public GetMaxPresetsResponse(int maxPresets) {
            this.maxPresets = maxPresets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceRemovePresets", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class ForceRemovePresetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public ForceRemovePresetsRequest() {
        }
        
        public ForceRemovePresetsRequest(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForceRemovePresetsResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class ForceRemovePresetsResponse {
        
        public ForceRemovePresetsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemovePresets", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class RemovePresetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public RemovePresetsRequest() {
        }
        
        public RemovePresetsRequest(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemovePresetsResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class RemovePresetsResponse {
        
        public RemovePresetsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GotoPreset", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GotoPresetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.PresetControl.GotoPreset move;
        
        public GotoPresetRequest() {
        }
        
        public GotoPresetRequest(PTZCameraTester.PresetControl.GotoPreset move) {
            this.move = move;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GotoPresetResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GotoPresetResponse {
        
        public GotoPresetResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateThumbnails", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GenerateThumbnailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public GenerateThumbnailsRequest() {
        }
        
        public GenerateThumbnailsRequest(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateThumbnailsResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GenerateThumbnailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("path", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] pathList;
        
        public GenerateThumbnailsResponse() {
        }
        
        public GenerateThumbnailsResponse(string[] pathList) {
            this.pathList = pathList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetTour", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class SetTourRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.PresetControl.SetTour tour;
        
        public SetTourRequest() {
        }
        
        public SetTourRequest(PTZCameraTester.PresetControl.SetTour tour) {
            this.tour = tour;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetTourResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class SetTourResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public SetTourResponse() {
        }
        
        public SetTourResponse(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTours", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetToursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public GetToursRequest() {
        }
        
        public GetToursRequest(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetToursResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetToursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tour", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Tour[] tourList;
        
        public GetToursResponse() {
        }
        
        public GetToursResponse(Tour[] tourList) {
            this.tourList = tourList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTourIds", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetTourIdsRequest {
        
        public GetTourIdsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTourIdsResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetTourIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public GetTourIdsResponse() {
        }
        
        public GetTourIdsResponse(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTourNames", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetTourNamesRequest {
        
        public GetTourNamesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTourNamesResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetTourNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Name[] nameList;
        
        public GetTourNamesResponse() {
        }
        
        public GetTourNamesResponse(Name[] nameList) {
            this.nameList = nameList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaxTours", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetMaxToursRequest {
        
        public GetMaxToursRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaxToursResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetMaxToursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxTours;
        
        public GetMaxToursResponse() {
        }
        
        public GetMaxToursResponse(int maxTours) {
            this.maxTours = maxTours;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaxPresetsPerTour", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetMaxPresetsPerTourRequest {
        
        public GetMaxPresetsPerTourRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaxPresetsPerTourResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class GetMaxPresetsPerTourResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxPresetsPerTour;
        
        public GetMaxPresetsPerTourResponse() {
        }
        
        public GetMaxPresetsPerTourResponse(int maxPresetsPerTour) {
            this.maxPresetsPerTour = maxPresetsPerTour;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveTours", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class RemoveToursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] idList;
        
        public RemoveToursRequest() {
        }
        
        public RemoveToursRequest(string[] idList) {
            this.idList = idList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveToursResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class RemoveToursResponse {
        
        public RemoveToursResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartTour", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class StartTourRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PresetControl:2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public StartTourRequest() {
        }
        
        public StartTourRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartTourResponse", WrapperNamespace="urn:schemas-pelco-com:service:PresetControl:2", IsWrapped=true)]
    public partial class StartTourResponse {
        
        public StartTourResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PresetControlPortTypeChannel : PTZCameraTester.PresetControl.PresetControlPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PresetControlPortTypeClient : System.ServiceModel.ClientBase<PTZCameraTester.PresetControl.PresetControlPortType>, PTZCameraTester.PresetControl.PresetControlPortType {
        
        public PresetControlPortTypeClient() {
        }
        
        public PresetControlPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PresetControlPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresetControlPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresetControlPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.ForceSetPresetResponse PTZCameraTester.PresetControl.PresetControlPortType.ForceSetPreset(PTZCameraTester.PresetControl.ForceSetPresetRequest request) {
            return base.Channel.ForceSetPreset(request);
        }
        
        public string ForceSetPreset(PTZCameraTester.PresetControl.SetPreset preset) {
            PTZCameraTester.PresetControl.ForceSetPresetRequest inValue = new PTZCameraTester.PresetControl.ForceSetPresetRequest();
            inValue.preset = preset;
            PTZCameraTester.PresetControl.ForceSetPresetResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).ForceSetPreset(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.SetPresetResponse PTZCameraTester.PresetControl.PresetControlPortType.SetPreset(PTZCameraTester.PresetControl.SetPresetRequest request) {
            return base.Channel.SetPreset(request);
        }
        
        public string SetPreset(PTZCameraTester.PresetControl.SetPreset preset) {
            PTZCameraTester.PresetControl.SetPresetRequest inValue = new PTZCameraTester.PresetControl.SetPresetRequest();
            inValue.preset = preset;
            PTZCameraTester.PresetControl.SetPresetResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).SetPreset(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetPresetsResponse PTZCameraTester.PresetControl.PresetControlPortType.GetPresets(PTZCameraTester.PresetControl.GetPresetsRequest request) {
            return base.Channel.GetPresets(request);
        }
        
        public Preset[] GetPresets(string[] idList) {
            PTZCameraTester.PresetControl.GetPresetsRequest inValue = new PTZCameraTester.PresetControl.GetPresetsRequest();
            inValue.idList = idList;
            PTZCameraTester.PresetControl.GetPresetsResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetPresets(inValue);
            return retVal.presetList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetPresetIdsResponse PTZCameraTester.PresetControl.PresetControlPortType.GetPresetIds(PTZCameraTester.PresetControl.GetPresetIdsRequest request) {
            return base.Channel.GetPresetIds(request);
        }
        
        public string[] GetPresetIds() {
            PTZCameraTester.PresetControl.GetPresetIdsRequest inValue = new PTZCameraTester.PresetControl.GetPresetIdsRequest();
            PTZCameraTester.PresetControl.GetPresetIdsResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetPresetIds(inValue);
            return retVal.idList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetPresetNamesResponse PTZCameraTester.PresetControl.PresetControlPortType.GetPresetNames(PTZCameraTester.PresetControl.GetPresetNamesRequest request) {
            return base.Channel.GetPresetNames(request);
        }
        
        public Name[] GetPresetNames() {
            PTZCameraTester.PresetControl.GetPresetNamesRequest inValue = new PTZCameraTester.PresetControl.GetPresetNamesRequest();
            PTZCameraTester.PresetControl.GetPresetNamesResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetPresetNames(inValue);
            return retVal.nameList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetMaxPresetsResponse PTZCameraTester.PresetControl.PresetControlPortType.GetMaxPresets(PTZCameraTester.PresetControl.GetMaxPresetsRequest request) {
            return base.Channel.GetMaxPresets(request);
        }
        
        public int GetMaxPresets() {
            PTZCameraTester.PresetControl.GetMaxPresetsRequest inValue = new PTZCameraTester.PresetControl.GetMaxPresetsRequest();
            PTZCameraTester.PresetControl.GetMaxPresetsResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetMaxPresets(inValue);
            return retVal.maxPresets;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.ForceRemovePresetsResponse PTZCameraTester.PresetControl.PresetControlPortType.ForceRemovePresets(PTZCameraTester.PresetControl.ForceRemovePresetsRequest request) {
            return base.Channel.ForceRemovePresets(request);
        }
        
        public void ForceRemovePresets(string[] idList) {
            PTZCameraTester.PresetControl.ForceRemovePresetsRequest inValue = new PTZCameraTester.PresetControl.ForceRemovePresetsRequest();
            inValue.idList = idList;
            PTZCameraTester.PresetControl.ForceRemovePresetsResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).ForceRemovePresets(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.RemovePresetsResponse PTZCameraTester.PresetControl.PresetControlPortType.RemovePresets(PTZCameraTester.PresetControl.RemovePresetsRequest request) {
            return base.Channel.RemovePresets(request);
        }
        
        public void RemovePresets(string[] idList) {
            PTZCameraTester.PresetControl.RemovePresetsRequest inValue = new PTZCameraTester.PresetControl.RemovePresetsRequest();
            inValue.idList = idList;
            PTZCameraTester.PresetControl.RemovePresetsResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).RemovePresets(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GotoPresetResponse PTZCameraTester.PresetControl.PresetControlPortType.GotoPreset(PTZCameraTester.PresetControl.GotoPresetRequest request) {
            return base.Channel.GotoPreset(request);
        }
        
        public void GotoPreset(PTZCameraTester.PresetControl.GotoPreset move) {
            PTZCameraTester.PresetControl.GotoPresetRequest inValue = new PTZCameraTester.PresetControl.GotoPresetRequest();
            inValue.move = move;
            PTZCameraTester.PresetControl.GotoPresetResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GotoPreset(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GenerateThumbnailsResponse PTZCameraTester.PresetControl.PresetControlPortType.GenerateThumbnails(PTZCameraTester.PresetControl.GenerateThumbnailsRequest request) {
            return base.Channel.GenerateThumbnails(request);
        }
        
        public string[] GenerateThumbnails(string[] idList) {
            PTZCameraTester.PresetControl.GenerateThumbnailsRequest inValue = new PTZCameraTester.PresetControl.GenerateThumbnailsRequest();
            inValue.idList = idList;
            PTZCameraTester.PresetControl.GenerateThumbnailsResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GenerateThumbnails(inValue);
            return retVal.pathList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.SetTourResponse PTZCameraTester.PresetControl.PresetControlPortType.SetTour(PTZCameraTester.PresetControl.SetTourRequest request) {
            return base.Channel.SetTour(request);
        }
        
        public string SetTour(PTZCameraTester.PresetControl.SetTour tour) {
            PTZCameraTester.PresetControl.SetTourRequest inValue = new PTZCameraTester.PresetControl.SetTourRequest();
            inValue.tour = tour;
            PTZCameraTester.PresetControl.SetTourResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).SetTour(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetToursResponse PTZCameraTester.PresetControl.PresetControlPortType.GetTours(PTZCameraTester.PresetControl.GetToursRequest request) {
            return base.Channel.GetTours(request);
        }
        
        public Tour[] GetTours(string[] idList) {
            PTZCameraTester.PresetControl.GetToursRequest inValue = new PTZCameraTester.PresetControl.GetToursRequest();
            inValue.idList = idList;
            PTZCameraTester.PresetControl.GetToursResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetTours(inValue);
            return retVal.tourList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetTourIdsResponse PTZCameraTester.PresetControl.PresetControlPortType.GetTourIds(PTZCameraTester.PresetControl.GetTourIdsRequest request) {
            return base.Channel.GetTourIds(request);
        }
        
        public string[] GetTourIds() {
            PTZCameraTester.PresetControl.GetTourIdsRequest inValue = new PTZCameraTester.PresetControl.GetTourIdsRequest();
            PTZCameraTester.PresetControl.GetTourIdsResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetTourIds(inValue);
            return retVal.idList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetTourNamesResponse PTZCameraTester.PresetControl.PresetControlPortType.GetTourNames(PTZCameraTester.PresetControl.GetTourNamesRequest request) {
            return base.Channel.GetTourNames(request);
        }
        
        public Name[] GetTourNames() {
            PTZCameraTester.PresetControl.GetTourNamesRequest inValue = new PTZCameraTester.PresetControl.GetTourNamesRequest();
            PTZCameraTester.PresetControl.GetTourNamesResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetTourNames(inValue);
            return retVal.nameList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetMaxToursResponse PTZCameraTester.PresetControl.PresetControlPortType.GetMaxTours(PTZCameraTester.PresetControl.GetMaxToursRequest request) {
            return base.Channel.GetMaxTours(request);
        }
        
        public int GetMaxTours() {
            PTZCameraTester.PresetControl.GetMaxToursRequest inValue = new PTZCameraTester.PresetControl.GetMaxToursRequest();
            PTZCameraTester.PresetControl.GetMaxToursResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetMaxTours(inValue);
            return retVal.maxTours;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.GetMaxPresetsPerTourResponse PTZCameraTester.PresetControl.PresetControlPortType.GetMaxPresetsPerTour(PTZCameraTester.PresetControl.GetMaxPresetsPerTourRequest request) {
            return base.Channel.GetMaxPresetsPerTour(request);
        }
        
        public int GetMaxPresetsPerTour() {
            PTZCameraTester.PresetControl.GetMaxPresetsPerTourRequest inValue = new PTZCameraTester.PresetControl.GetMaxPresetsPerTourRequest();
            PTZCameraTester.PresetControl.GetMaxPresetsPerTourResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).GetMaxPresetsPerTour(inValue);
            return retVal.maxPresetsPerTour;
        }
        
        public void StopTour() {
            base.Channel.StopTour();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.RemoveToursResponse PTZCameraTester.PresetControl.PresetControlPortType.RemoveTours(PTZCameraTester.PresetControl.RemoveToursRequest request) {
            return base.Channel.RemoveTours(request);
        }
        
        public void RemoveTours(string[] idList) {
            PTZCameraTester.PresetControl.RemoveToursRequest inValue = new PTZCameraTester.PresetControl.RemoveToursRequest();
            inValue.idList = idList;
            PTZCameraTester.PresetControl.RemoveToursResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).RemoveTours(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PresetControl.StartTourResponse PTZCameraTester.PresetControl.PresetControlPortType.StartTour(PTZCameraTester.PresetControl.StartTourRequest request) {
            return base.Channel.StartTour(request);
        }
        
        public void StartTour(string id) {
            PTZCameraTester.PresetControl.StartTourRequest inValue = new PTZCameraTester.PresetControl.StartTourRequest();
            inValue.id = id;
            PTZCameraTester.PresetControl.StartTourResponse retVal = ((PTZCameraTester.PresetControl.PresetControlPortType)(this)).StartTour(inValue);
        }
    }
}
