//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZCameraTester.AudioOutput {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", ConfigurationName="AudioOutput.AudioOutputPortType")]
    public interface AudioOutputPortType {
        
        // CODEGEN: Parameter 'streamCatalog' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="streamCatalog")]
        PTZCameraTester.AudioOutput.QueryResponse Query(PTZCameraTester.AudioOutput.QueryRequest request);
        
        // CODEGEN: Parameter 'streamParameters' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#Connect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.AudioOutput.ConnectResponse Connect(PTZCameraTester.AudioOutput.ConnectRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#Disconnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.AudioOutput.DisconnectResponse Disconnect(PTZCameraTester.AudioOutput.DisconnectRequest request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#RefreshSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.AudioOutput.RefreshSessionResponse RefreshSession(PTZCameraTester.AudioOutput.RefreshSessionRequest request);
        
        // CODEGEN: Parameter 'activeSessions' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#GetActiveSessions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="activeSessions")]
        PTZCameraTester.AudioOutput.GetActiveSessionsResponse GetActiveSessions(PTZCameraTester.AudioOutput.GetActiveSessionsRequest request);
        
        // CODEGEN: Parameter 'sessionIds' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#GetActiveSessionIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sessionIds")]
        PTZCameraTester.AudioOutput.GetActiveSessionIdsResponse GetActiveSessionIds(PTZCameraTester.AudioOutput.GetActiveSessionIdsRequest request);
        
        // CODEGEN: Parameter 'streamParameters' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#GetSessionParameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="streamParameters")]
        PTZCameraTester.AudioOutput.GetSessionParametersResponse GetSessionParameters(PTZCameraTester.AudioOutput.GetSessionParametersRequest request);
        
        // CODEGEN: Parameter 'sourceUDN' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#SetStreamPriority", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.AudioOutput.SetStreamPriorityResponse SetStreamPriority(PTZCameraTester.AudioOutput.SetStreamPriorityRequest request);
        
        // CODEGEN: Parameter 'streamCatalog' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:AudioOutput:1#GetStreamPriority", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="streamCatalog")]
        PTZCameraTester.AudioOutput.GetStreamPriorityResponse GetStreamPriority(PTZCameraTester.AudioOutput.GetStreamPriorityRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public partial class StreamQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceURIField;
        
        private string sourceIdField;
        
        private string outputUDNField;
        
        private string outputIdField;
        
        private string eventUDNField;
        
        private string eventIdField;
        
        private EVENTURN eventURNField;
        
        private bool eventURNFieldSpecified;
        
        private string serviceIdField;
        
        private string formatsField;
        
        private string selectedField;
        
        private int minBitrateField;
        
        private bool minBitrateFieldSpecified;
        
        private int maxBitrateField;
        
        private bool maxBitrateFieldSpecified;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private PageHeader pageHeaderField;
        
        private string deletionPriorityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sourceURI {
            get {
                return this.sourceURIField;
            }
            set {
                this.sourceURIField = value;
                this.RaisePropertyChanged("sourceURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
                this.RaisePropertyChanged("sourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string outputUDN {
            get {
                return this.outputUDNField;
            }
            set {
                this.outputUDNField = value;
                this.RaisePropertyChanged("outputUDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string outputId {
            get {
                return this.outputIdField;
            }
            set {
                this.outputIdField = value;
                this.RaisePropertyChanged("outputId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string eventUDN {
            get {
                return this.eventUDNField;
            }
            set {
                this.eventUDNField = value;
                this.RaisePropertyChanged("eventUDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string eventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
                this.RaisePropertyChanged("eventId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public EVENTURN eventURN {
            get {
                return this.eventURNField;
            }
            set {
                this.eventURNField = value;
                this.RaisePropertyChanged("eventURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventURNSpecified {
            get {
                return this.eventURNFieldSpecified;
            }
            set {
                this.eventURNFieldSpecified = value;
                this.RaisePropertyChanged("eventURNSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string formats {
            get {
                return this.formatsField;
            }
            set {
                this.formatsField = value;
                this.RaisePropertyChanged("formats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("selected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int minBitrate {
            get {
                return this.minBitrateField;
            }
            set {
                this.minBitrateField = value;
                this.RaisePropertyChanged("minBitrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minBitrateSpecified {
            get {
                return this.minBitrateFieldSpecified;
            }
            set {
                this.minBitrateFieldSpecified = value;
                this.RaisePropertyChanged("minBitrateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int maxBitrate {
            get {
                return this.maxBitrateField;
            }
            set {
                this.maxBitrateField = value;
                this.RaisePropertyChanged("maxBitrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxBitrateSpecified {
            get {
                return this.maxBitrateFieldSpecified;
            }
            set {
                this.maxBitrateFieldSpecified = value;
                this.RaisePropertyChanged("maxBitrateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public PageHeader pageHeader {
            get {
                return this.pageHeaderField;
            }
            set {
                this.pageHeaderField = value;
                this.RaisePropertyChanged("pageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string deletionPriority {
            get {
                return this.deletionPriorityField;
            }
            set {
                this.deletionPriorityField = value;
                this.RaisePropertyChanged("deletionPriority");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="EVENT-URN", Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public enum EVENTURN {
        
        /// <remarks/>
        AlarmRecord,
        
        /// <remarks/>
        MotionRecord,
        
        /// <remarks/>
        TimedRecord,
        
        /// <remarks/>
        MarkRecord,
        
        /// <remarks/>
        AllRecord,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public partial class PageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private QueryId queryIdField;
        
        private uint nextEntryField;
        
        private bool nextEntryFieldSpecified;
        
        private uint totalEntriesField;
        
        private bool totalEntriesFieldSpecified;
        
        private uint maxEntriesField;
        
        private bool maxEntriesFieldSpecified;
        
        private string resultURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public QueryId queryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
                this.RaisePropertyChanged("queryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public uint nextEntry {
            get {
                return this.nextEntryField;
            }
            set {
                this.nextEntryField = value;
                this.RaisePropertyChanged("nextEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nextEntrySpecified {
            get {
                return this.nextEntryFieldSpecified;
            }
            set {
                this.nextEntryFieldSpecified = value;
                this.RaisePropertyChanged("nextEntrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public uint totalEntries {
            get {
                return this.totalEntriesField;
            }
            set {
                this.totalEntriesField = value;
                this.RaisePropertyChanged("totalEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalEntriesSpecified {
            get {
                return this.totalEntriesFieldSpecified;
            }
            set {
                this.totalEntriesFieldSpecified = value;
                this.RaisePropertyChanged("totalEntriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public uint maxEntries {
            get {
                return this.maxEntriesField;
            }
            set {
                this.maxEntriesField = value;
                this.RaisePropertyChanged("maxEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxEntriesSpecified {
            get {
                return this.maxEntriesFieldSpecified;
            }
            set {
                this.maxEntriesFieldSpecified = value;
                this.RaisePropertyChanged("maxEntriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string resultURI {
            get {
                return this.resultURIField;
            }
            set {
                this.resultURIField = value;
                this.RaisePropertyChanged("resultURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public partial class QueryId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint ttlField;
        
        private bool ttlFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
                this.RaisePropertyChanged("ttl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttlSpecified {
            get {
                return this.ttlFieldSpecified;
            }
            set {
                this.ttlFieldSpecified = value;
                this.RaisePropertyChanged("ttlSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public partial class AudioQuality : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int framerateField;
        
        private int bitrateField;
        
        private string formatField;
        
        private int samplesizeField;
        
        private int samplerateField;
        
        private int volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int framerate {
            get {
                return this.framerateField;
            }
            set {
                this.framerateField = value;
                this.RaisePropertyChanged("framerate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int bitrate {
            get {
                return this.bitrateField;
            }
            set {
                this.bitrateField = value;
                this.RaisePropertyChanged("bitrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int samplesize {
            get {
                return this.samplesizeField;
            }
            set {
                this.samplesizeField = value;
                this.RaisePropertyChanged("samplesize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int samplerate {
            get {
                return this.samplerateField;
            }
            set {
                this.samplerateField = value;
                this.RaisePropertyChanged("samplerate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("volume");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public partial class StreamSession : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceURIField;
        
        private string outputURIField;
        
        private string controlURIField;
        
        private string transportURLField;
        
        private string streamStateField;
        
        private string sessionIdField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private int clientsField;
        
        private bool clientsFieldSpecified;
        
        private int refreshIntervalField;
        
        private int transportUrlUseSourceAddressField;
        
        private bool transportUrlUseSourceAddressFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sourceURI {
            get {
                return this.sourceURIField;
            }
            set {
                this.sourceURIField = value;
                this.RaisePropertyChanged("sourceURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string outputURI {
            get {
                return this.outputURIField;
            }
            set {
                this.outputURIField = value;
                this.RaisePropertyChanged("outputURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string controlURI {
            get {
                return this.controlURIField;
            }
            set {
                this.controlURIField = value;
                this.RaisePropertyChanged("controlURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string transportURL {
            get {
                return this.transportURLField;
            }
            set {
                this.transportURLField = value;
                this.RaisePropertyChanged("transportURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string streamState {
            get {
                return this.streamStateField;
            }
            set {
                this.streamStateField = value;
                this.RaisePropertyChanged("streamState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int clients {
            get {
                return this.clientsField;
            }
            set {
                this.clientsField = value;
                this.RaisePropertyChanged("clients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientsSpecified {
            get {
                return this.clientsFieldSpecified;
            }
            set {
                this.clientsFieldSpecified = value;
                this.RaisePropertyChanged("clientsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int refreshInterval {
            get {
                return this.refreshIntervalField;
            }
            set {
                this.refreshIntervalField = value;
                this.RaisePropertyChanged("refreshInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int transportUrlUseSourceAddress {
            get {
                return this.transportUrlUseSourceAddressField;
            }
            set {
                this.transportUrlUseSourceAddressField = value;
                this.RaisePropertyChanged("transportUrlUseSourceAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transportUrlUseSourceAddressSpecified {
            get {
                return this.transportUrlUseSourceAddressFieldSpecified;
            }
            set {
                this.transportUrlUseSourceAddressFieldSpecified = value;
                this.RaisePropertyChanged("transportUrlUseSourceAddressSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public partial class StreamParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string displayNameField;
        
        private string eventTypeField;
        
        private int preAlarmDurationInManualRecordField;
        
        private StreamSession streamSessionField;
        
        private AudioQuality audioQualityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("displayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("eventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int preAlarmDurationInManualRecord {
            get {
                return this.preAlarmDurationInManualRecordField;
            }
            set {
                this.preAlarmDurationInManualRecordField = value;
                this.RaisePropertyChanged("preAlarmDurationInManualRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public StreamSession streamSession {
            get {
                return this.streamSessionField;
            }
            set {
                this.streamSessionField = value;
                this.RaisePropertyChanged("streamSession");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public AudioQuality audioQuality {
            get {
                return this.audioQualityField;
            }
            set {
                this.audioQualityField = value;
                this.RaisePropertyChanged("audioQuality");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1")]
    public partial class StreamCatalog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PageHeader pageHeaderField;
        
        private StreamParameters[] entriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PageHeader pageHeader {
            get {
                return this.pageHeaderField;
            }
            set {
                this.pageHeaderField = value;
                this.RaisePropertyChanged("pageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("streamParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StreamParameters[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
                this.RaisePropertyChanged("entries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Query", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AudioOutput.StreamQuery streamQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int asyncId;
        
        public QueryRequest() {
        }
        
        public QueryRequest(PTZCameraTester.AudioOutput.StreamQuery streamQuery, int asyncId) {
            this.streamQuery = streamQuery;
            this.asyncId = asyncId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AudioOutput.StreamCatalog streamCatalog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int asyncId;
        
        public QueryResponse() {
        }
        
        public QueryResponse(PTZCameraTester.AudioOutput.StreamCatalog streamCatalog, int asyncId) {
            this.streamCatalog = streamCatalog;
            this.asyncId = asyncId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Connect", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class ConnectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AudioOutput.StreamParameters streamParameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int asyncId;
        
        public ConnectRequest() {
        }
        
        public ConnectRequest(PTZCameraTester.AudioOutput.StreamParameters streamParameters, int asyncId) {
            this.streamParameters = streamParameters;
            this.asyncId = asyncId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConnectResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class ConnectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AudioOutput.StreamParameters streamParameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int asyncId;
        
        public ConnectResponse() {
        }
        
        public ConnectResponse(PTZCameraTester.AudioOutput.StreamParameters streamParameters, int asyncId) {
            this.streamParameters = streamParameters;
            this.asyncId = asyncId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Disconnect", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class DisconnectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int asyncId;
        
        public DisconnectRequest() {
        }
        
        public DisconnectRequest(string sessionId, int asyncId) {
            this.sessionId = sessionId;
            this.asyncId = asyncId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisconnectResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class DisconnectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int asyncId;
        
        public DisconnectResponse() {
        }
        
        public DisconnectResponse(int asyncId) {
            this.asyncId = asyncId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefreshSession", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class RefreshSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int refreshInterval;
        
        public RefreshSessionRequest() {
        }
        
        public RefreshSessionRequest(string sessionId, int refreshInterval) {
            this.sessionId = sessionId;
            this.refreshInterval = refreshInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefreshSessionResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class RefreshSessionResponse {
        
        public RefreshSessionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActiveSessions", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetActiveSessionsRequest {
        
        public GetActiveSessionsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActiveSessionsResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetActiveSessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int activeSessions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxSessions;
        
        public GetActiveSessionsResponse() {
        }
        
        public GetActiveSessionsResponse(int activeSessions, int maxSessions) {
            this.activeSessions = activeSessions;
            this.maxSessions = maxSessions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActiveSessionIds", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetActiveSessionIdsRequest {
        
        public GetActiveSessionIdsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActiveSessionIdsResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetActiveSessionIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("session", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] sessionIds;
        
        public GetActiveSessionIdsResponse() {
        }
        
        public GetActiveSessionIdsResponse(string[] sessionIds) {
            this.sessionIds = sessionIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSessionParameters", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetSessionParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        public GetSessionParametersRequest() {
        }
        
        public GetSessionParametersRequest(string sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSessionParametersResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetSessionParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AudioOutput.StreamParameters streamParameters;
        
        public GetSessionParametersResponse() {
        }
        
        public GetSessionParametersResponse(PTZCameraTester.AudioOutput.StreamParameters streamParameters) {
            this.streamParameters = streamParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetStreamPriority", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class SetStreamPriorityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sourceUDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment;
        
        public SetStreamPriorityRequest() {
        }
        
        public SetStreamPriorityRequest(string sourceUDN, string startTime, string endTime, int priority, string comment) {
            this.sourceUDN = sourceUDN;
            this.startTime = startTime;
            this.endTime = endTime;
            this.priority = priority;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetStreamPriorityResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class SetStreamPriorityResponse {
        
        public SetStreamPriorityResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStreamPriority", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetStreamPriorityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sourceUDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endTime;
        
        public GetStreamPriorityRequest() {
        }
        
        public GetStreamPriorityRequest(string sourceUDN, string startTime, string endTime) {
            this.sourceUDN = sourceUDN;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStreamPriorityResponse", WrapperNamespace="urn:schemas-pelco-com:service:AudioOutput:1", IsWrapped=true)]
    public partial class GetStreamPriorityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:AudioOutput:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.AudioOutput.StreamCatalog streamCatalog;
        
        public GetStreamPriorityResponse() {
        }
        
        public GetStreamPriorityResponse(PTZCameraTester.AudioOutput.StreamCatalog streamCatalog) {
            this.streamCatalog = streamCatalog;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AudioOutputPortTypeChannel : PTZCameraTester.AudioOutput.AudioOutputPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AudioOutputPortTypeClient : System.ServiceModel.ClientBase<PTZCameraTester.AudioOutput.AudioOutputPortType>, PTZCameraTester.AudioOutput.AudioOutputPortType {
        
        public AudioOutputPortTypeClient() {
        }
        
        public AudioOutputPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AudioOutputPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudioOutputPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudioOutputPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.QueryResponse PTZCameraTester.AudioOutput.AudioOutputPortType.Query(PTZCameraTester.AudioOutput.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public PTZCameraTester.AudioOutput.StreamCatalog Query(PTZCameraTester.AudioOutput.StreamQuery streamQuery, ref int asyncId) {
            PTZCameraTester.AudioOutput.QueryRequest inValue = new PTZCameraTester.AudioOutput.QueryRequest();
            inValue.streamQuery = streamQuery;
            inValue.asyncId = asyncId;
            PTZCameraTester.AudioOutput.QueryResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).Query(inValue);
            asyncId = retVal.asyncId;
            return retVal.streamCatalog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.ConnectResponse PTZCameraTester.AudioOutput.AudioOutputPortType.Connect(PTZCameraTester.AudioOutput.ConnectRequest request) {
            return base.Channel.Connect(request);
        }
        
        public void Connect(ref PTZCameraTester.AudioOutput.StreamParameters streamParameters, ref int asyncId) {
            PTZCameraTester.AudioOutput.ConnectRequest inValue = new PTZCameraTester.AudioOutput.ConnectRequest();
            inValue.streamParameters = streamParameters;
            inValue.asyncId = asyncId;
            PTZCameraTester.AudioOutput.ConnectResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).Connect(inValue);
            streamParameters = retVal.streamParameters;
            asyncId = retVal.asyncId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.DisconnectResponse PTZCameraTester.AudioOutput.AudioOutputPortType.Disconnect(PTZCameraTester.AudioOutput.DisconnectRequest request) {
            return base.Channel.Disconnect(request);
        }
        
        public void Disconnect(string sessionId, ref int asyncId) {
            PTZCameraTester.AudioOutput.DisconnectRequest inValue = new PTZCameraTester.AudioOutput.DisconnectRequest();
            inValue.sessionId = sessionId;
            inValue.asyncId = asyncId;
            PTZCameraTester.AudioOutput.DisconnectResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).Disconnect(inValue);
            asyncId = retVal.asyncId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.RefreshSessionResponse PTZCameraTester.AudioOutput.AudioOutputPortType.RefreshSession(PTZCameraTester.AudioOutput.RefreshSessionRequest request) {
            return base.Channel.RefreshSession(request);
        }
        
        public void RefreshSession(string sessionId, int refreshInterval) {
            PTZCameraTester.AudioOutput.RefreshSessionRequest inValue = new PTZCameraTester.AudioOutput.RefreshSessionRequest();
            inValue.sessionId = sessionId;
            inValue.refreshInterval = refreshInterval;
            PTZCameraTester.AudioOutput.RefreshSessionResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).RefreshSession(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.GetActiveSessionsResponse PTZCameraTester.AudioOutput.AudioOutputPortType.GetActiveSessions(PTZCameraTester.AudioOutput.GetActiveSessionsRequest request) {
            return base.Channel.GetActiveSessions(request);
        }
        
        public int GetActiveSessions(out int maxSessions) {
            PTZCameraTester.AudioOutput.GetActiveSessionsRequest inValue = new PTZCameraTester.AudioOutput.GetActiveSessionsRequest();
            PTZCameraTester.AudioOutput.GetActiveSessionsResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).GetActiveSessions(inValue);
            maxSessions = retVal.maxSessions;
            return retVal.activeSessions;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.GetActiveSessionIdsResponse PTZCameraTester.AudioOutput.AudioOutputPortType.GetActiveSessionIds(PTZCameraTester.AudioOutput.GetActiveSessionIdsRequest request) {
            return base.Channel.GetActiveSessionIds(request);
        }
        
        public string[] GetActiveSessionIds() {
            PTZCameraTester.AudioOutput.GetActiveSessionIdsRequest inValue = new PTZCameraTester.AudioOutput.GetActiveSessionIdsRequest();
            PTZCameraTester.AudioOutput.GetActiveSessionIdsResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).GetActiveSessionIds(inValue);
            return retVal.sessionIds;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.GetSessionParametersResponse PTZCameraTester.AudioOutput.AudioOutputPortType.GetSessionParameters(PTZCameraTester.AudioOutput.GetSessionParametersRequest request) {
            return base.Channel.GetSessionParameters(request);
        }
        
        public PTZCameraTester.AudioOutput.StreamParameters GetSessionParameters(string sessionId) {
            PTZCameraTester.AudioOutput.GetSessionParametersRequest inValue = new PTZCameraTester.AudioOutput.GetSessionParametersRequest();
            inValue.sessionId = sessionId;
            PTZCameraTester.AudioOutput.GetSessionParametersResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).GetSessionParameters(inValue);
            return retVal.streamParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.SetStreamPriorityResponse PTZCameraTester.AudioOutput.AudioOutputPortType.SetStreamPriority(PTZCameraTester.AudioOutput.SetStreamPriorityRequest request) {
            return base.Channel.SetStreamPriority(request);
        }
        
        public void SetStreamPriority(string sourceUDN, string startTime, string endTime, int priority, string comment) {
            PTZCameraTester.AudioOutput.SetStreamPriorityRequest inValue = new PTZCameraTester.AudioOutput.SetStreamPriorityRequest();
            inValue.sourceUDN = sourceUDN;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            inValue.priority = priority;
            inValue.comment = comment;
            PTZCameraTester.AudioOutput.SetStreamPriorityResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).SetStreamPriority(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.AudioOutput.GetStreamPriorityResponse PTZCameraTester.AudioOutput.AudioOutputPortType.GetStreamPriority(PTZCameraTester.AudioOutput.GetStreamPriorityRequest request) {
            return base.Channel.GetStreamPriority(request);
        }
        
        public PTZCameraTester.AudioOutput.StreamCatalog GetStreamPriority(string sourceUDN, string startTime, string endTime) {
            PTZCameraTester.AudioOutput.GetStreamPriorityRequest inValue = new PTZCameraTester.AudioOutput.GetStreamPriorityRequest();
            inValue.sourceUDN = sourceUDN;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            PTZCameraTester.AudioOutput.GetStreamPriorityResponse retVal = ((PTZCameraTester.AudioOutput.AudioOutputPortType)(this)).GetStreamPriority(inValue);
            return retVal.streamCatalog;
        }
    }
}
