//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZCameraTester.PelcoConfiguration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", ConfigurationName="PelcoConfiguration.PelcoConfigurationPortType")]
    public interface PelcoConfigurationPortType {
        
        // CODEGEN: Parameter 'location' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#GetLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="location")]
        PTZCameraTester.PelcoConfiguration.GetLocationResponse GetLocation(PTZCameraTester.PelcoConfiguration.GetLocationRequest request);
        
        // CODEGEN: Parameter 'location' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#SetDescription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PTZCameraTester.PelcoConfiguration.SetDescriptionResponse SetDescription(PTZCameraTester.PelcoConfiguration.SetDescriptionRequest request);
        
        // CODEGEN: Parameter 'modelName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#SetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        PTZCameraTester.PelcoConfiguration.SetConfigurationResponse SetConfiguration(PTZCameraTester.PelcoConfiguration.SetConfigurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#ResetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        void ResetConfiguration();
        
        // CODEGEN: Parameter 'modelName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#Restart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        PTZCameraTester.PelcoConfiguration.RestartResponse Restart(PTZCameraTester.PelcoConfiguration.RestartRequest request);
        
        // CODEGEN: Parameter 'pelcoConfig' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#GetConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pelcoConfig")]
        PTZCameraTester.PelcoConfiguration.GetConfigurationResponse GetConfiguration(PTZCameraTester.PelcoConfiguration.GetConfigurationRequest request);
        
        // CODEGEN: Parameter 'modelName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#GetModelName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="modelName")]
        PTZCameraTester.PelcoConfiguration.GetModelNameResponse GetModelName(PTZCameraTester.PelcoConfiguration.GetModelNameRequest request);
        
        // CODEGEN: Parameter 'modelNumber' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#GetModelNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="modelNumber")]
        PTZCameraTester.PelcoConfiguration.GetModelNumberResponse GetModelNumber(PTZCameraTester.PelcoConfiguration.GetModelNumberRequest request);
        
        // CODEGEN: Parameter 'modelName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#ResetSecurity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        PTZCameraTester.PelcoConfiguration.ResetSecurityResponse ResetSecurity(PTZCameraTester.PelcoConfiguration.ResetSecurityRequest request);
        
        // CODEGEN: Parameter 'modelName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#ResetSynced", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        PTZCameraTester.PelcoConfiguration.ResetSyncedResponse ResetSynced(PTZCameraTester.PelcoConfiguration.ResetSyncedRequest request);
        
        // CODEGEN: Parameter 'isRegistered' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas-pelco-com:service:PelcoConfiguration:1#IsRegistered", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Port))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isRegistered")]
        PTZCameraTester.PelcoConfiguration.IsRegisteredResponse IsRegistered(PTZCameraTester.PelcoConfiguration.IsRegisteredRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocation", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetLocationRequest {
        
        public GetLocationRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLocationResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string location;
        
        public GetLocationResponse() {
        }
        
        public GetLocationResponse(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDescription", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class SetDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string actionVersion;
        
        public SetDescriptionRequest() {
        }
        
        public SetDescriptionRequest(string location, string actionVersion) {
            this.location = location;
            this.actionVersion = actionVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetDescriptionResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class SetDescriptionResponse {
        
        public SetDescriptionResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1")]
    public partial class PelcoConfig : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int renewIntervalField;
        
        private int startupIntervalField;
        
        private string ntpAddressField;
        
        private bool shutdownWatchdogTimeoutField;
        
        private bool isDefaultField;
        
        private bool isDefaultFieldSpecified;
        
        private bool allowSystemUpdateField;
        
        private bool allowSystemUpdateFieldSpecified;
        
        private bool isSyncedField;
        
        private bool isSyncedFieldSpecified;
        
        private bool dstChangeTimeField;
        
        private bool dstChangeTimeFieldSpecified;
        
        private int dstOffsetField;
        
        private bool dstOffsetFieldSpecified;
        
        private int gmtOffsetField;
        
        private bool gmtOffsetFieldSpecified;
        
        private SSDP ssdpField;
        
        private ThreadPool threadPoolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int renewInterval {
            get {
                return this.renewIntervalField;
            }
            set {
                this.renewIntervalField = value;
                this.RaisePropertyChanged("renewInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int startupInterval {
            get {
                return this.startupIntervalField;
            }
            set {
                this.startupIntervalField = value;
                this.RaisePropertyChanged("startupInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ntpAddress {
            get {
                return this.ntpAddressField;
            }
            set {
                this.ntpAddressField = value;
                this.RaisePropertyChanged("ntpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool shutdownWatchdogTimeout {
            get {
                return this.shutdownWatchdogTimeoutField;
            }
            set {
                this.shutdownWatchdogTimeoutField = value;
                this.RaisePropertyChanged("shutdownWatchdogTimeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
                this.RaisePropertyChanged("isDefault");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDefaultSpecified {
            get {
                return this.isDefaultFieldSpecified;
            }
            set {
                this.isDefaultFieldSpecified = value;
                this.RaisePropertyChanged("isDefaultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool allowSystemUpdate {
            get {
                return this.allowSystemUpdateField;
            }
            set {
                this.allowSystemUpdateField = value;
                this.RaisePropertyChanged("allowSystemUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allowSystemUpdateSpecified {
            get {
                return this.allowSystemUpdateFieldSpecified;
            }
            set {
                this.allowSystemUpdateFieldSpecified = value;
                this.RaisePropertyChanged("allowSystemUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool isSynced {
            get {
                return this.isSyncedField;
            }
            set {
                this.isSyncedField = value;
                this.RaisePropertyChanged("isSynced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSyncedSpecified {
            get {
                return this.isSyncedFieldSpecified;
            }
            set {
                this.isSyncedFieldSpecified = value;
                this.RaisePropertyChanged("isSyncedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool dstChangeTime {
            get {
                return this.dstChangeTimeField;
            }
            set {
                this.dstChangeTimeField = value;
                this.RaisePropertyChanged("dstChangeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dstChangeTimeSpecified {
            get {
                return this.dstChangeTimeFieldSpecified;
            }
            set {
                this.dstChangeTimeFieldSpecified = value;
                this.RaisePropertyChanged("dstChangeTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int dstOffset {
            get {
                return this.dstOffsetField;
            }
            set {
                this.dstOffsetField = value;
                this.RaisePropertyChanged("dstOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dstOffsetSpecified {
            get {
                return this.dstOffsetFieldSpecified;
            }
            set {
                this.dstOffsetFieldSpecified = value;
                this.RaisePropertyChanged("dstOffsetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int gmtOffset {
            get {
                return this.gmtOffsetField;
            }
            set {
                this.gmtOffsetField = value;
                this.RaisePropertyChanged("gmtOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gmtOffsetSpecified {
            get {
                return this.gmtOffsetFieldSpecified;
            }
            set {
                this.gmtOffsetFieldSpecified = value;
                this.RaisePropertyChanged("gmtOffsetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public SSDP ssdp {
            get {
                return this.ssdpField;
            }
            set {
                this.ssdpField = value;
                this.RaisePropertyChanged("ssdp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ThreadPool threadPool {
            get {
                return this.threadPoolField;
            }
            set {
                this.threadPoolField = value;
                this.RaisePropertyChanged("threadPool");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1")]
    public partial class SSDP : Port {
        
        private int ttlField;
        
        private bool ttlFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
                this.RaisePropertyChanged("ttl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttlSpecified {
            get {
                return this.ttlFieldSpecified;
            }
            set {
                this.ttlFieldSpecified = value;
                this.RaisePropertyChanged("ttlSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SSDP))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1")]
    public partial class Port : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool inField;
        
        private bool inFieldSpecified;
        
        private bool outField;
        
        private bool outFieldSpecified;
        
        private bool searchField;
        
        private bool searchFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @in {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
                this.RaisePropertyChanged("in");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inSpecified {
            get {
                return this.inFieldSpecified;
            }
            set {
                this.inFieldSpecified = value;
                this.RaisePropertyChanged("inSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
                this.RaisePropertyChanged("out");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool outSpecified {
            get {
                return this.outFieldSpecified;
            }
            set {
                this.outFieldSpecified = value;
                this.RaisePropertyChanged("outSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool search {
            get {
                return this.searchField;
            }
            set {
                this.searchField = value;
                this.RaisePropertyChanged("search");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchSpecified {
            get {
                return this.searchFieldSpecified;
            }
            set {
                this.searchFieldSpecified = value;
                this.RaisePropertyChanged("searchSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1")]
    public partial class ThreadPool : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int minThreadsField;
        
        private int maxThreadsField;
        
        private int jobsPerThreadField;
        
        private int threadIdleTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int minThreads {
            get {
                return this.minThreadsField;
            }
            set {
                this.minThreadsField = value;
                this.RaisePropertyChanged("minThreads");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int maxThreads {
            get {
                return this.maxThreadsField;
            }
            set {
                this.maxThreadsField = value;
                this.RaisePropertyChanged("maxThreads");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int jobsPerThread {
            get {
                return this.jobsPerThreadField;
            }
            set {
                this.jobsPerThreadField = value;
                this.RaisePropertyChanged("jobsPerThread");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int threadIdleTime {
            get {
                return this.threadIdleTimeField;
            }
            set {
                this.threadIdleTimeField = value;
                this.RaisePropertyChanged("threadIdleTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class SetConfigurationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.PelcoConfiguration.PelcoConfig pelcoConfig;
        
        public SetConfigurationRequest() {
        }
        
        public SetConfigurationRequest(string modelName, PTZCameraTester.PelcoConfiguration.PelcoConfig pelcoConfig) {
            this.modelName = modelName;
            this.pelcoConfig = pelcoConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class SetConfigurationResponse {
        
        public SetConfigurationResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Restart", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class RestartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelName;
        
        public RestartRequest() {
        }
        
        public RestartRequest(string modelName) {
            this.modelName = modelName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RestartResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class RestartResponse {
        
        public RestartResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfiguration", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetConfigurationRequest {
        
        public GetConfigurationRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConfigurationResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetConfigurationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PTZCameraTester.PelcoConfiguration.PelcoConfig pelcoConfig;
        
        public GetConfigurationResponse() {
        }
        
        public GetConfigurationResponse(PTZCameraTester.PelcoConfiguration.PelcoConfig pelcoConfig) {
            this.pelcoConfig = pelcoConfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelName", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetModelNameRequest {
        
        public GetModelNameRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelNameResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetModelNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelName;
        
        public GetModelNameResponse() {
        }
        
        public GetModelNameResponse(string modelName) {
            this.modelName = modelName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelNumber", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetModelNumberRequest {
        
        public GetModelNumberRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelNumberResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class GetModelNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelNumber;
        
        public GetModelNumberResponse() {
        }
        
        public GetModelNumberResponse(string modelNumber) {
            this.modelNumber = modelNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetSecurity", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class ResetSecurityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelName;
        
        public ResetSecurityRequest() {
        }
        
        public ResetSecurityRequest(string modelName) {
            this.modelName = modelName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetSecurityResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class ResetSecurityResponse {
        
        public ResetSecurityResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetSynced", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class ResetSyncedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelName;
        
        public ResetSyncedRequest() {
        }
        
        public ResetSyncedRequest(string modelName) {
            this.modelName = modelName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetSyncedResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class ResetSyncedResponse {
        
        public ResetSyncedResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsRegistered", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class IsRegisteredRequest {
        
        public IsRegisteredRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsRegisteredResponse", WrapperNamespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", IsWrapped=true)]
    public partial class IsRegisteredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-pelco-com:service:PelcoConfiguration:1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isRegistered;
        
        public IsRegisteredResponse() {
        }
        
        public IsRegisteredResponse(int isRegistered) {
            this.isRegistered = isRegistered;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PelcoConfigurationPortTypeChannel : PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PelcoConfigurationPortTypeClient : System.ServiceModel.ClientBase<PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType>, PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType {
        
        public PelcoConfigurationPortTypeClient() {
        }
        
        public PelcoConfigurationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PelcoConfigurationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PelcoConfigurationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PelcoConfigurationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.GetLocationResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.GetLocation(PTZCameraTester.PelcoConfiguration.GetLocationRequest request) {
            return base.Channel.GetLocation(request);
        }
        
        public string GetLocation() {
            PTZCameraTester.PelcoConfiguration.GetLocationRequest inValue = new PTZCameraTester.PelcoConfiguration.GetLocationRequest();
            PTZCameraTester.PelcoConfiguration.GetLocationResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).GetLocation(inValue);
            return retVal.location;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.SetDescriptionResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.SetDescription(PTZCameraTester.PelcoConfiguration.SetDescriptionRequest request) {
            return base.Channel.SetDescription(request);
        }
        
        public void SetDescription(string location, string actionVersion) {
            PTZCameraTester.PelcoConfiguration.SetDescriptionRequest inValue = new PTZCameraTester.PelcoConfiguration.SetDescriptionRequest();
            inValue.location = location;
            inValue.actionVersion = actionVersion;
            PTZCameraTester.PelcoConfiguration.SetDescriptionResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).SetDescription(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.SetConfigurationResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.SetConfiguration(PTZCameraTester.PelcoConfiguration.SetConfigurationRequest request) {
            return base.Channel.SetConfiguration(request);
        }
        
        public void SetConfiguration(string modelName, PTZCameraTester.PelcoConfiguration.PelcoConfig pelcoConfig) {
            PTZCameraTester.PelcoConfiguration.SetConfigurationRequest inValue = new PTZCameraTester.PelcoConfiguration.SetConfigurationRequest();
            inValue.modelName = modelName;
            inValue.pelcoConfig = pelcoConfig;
            PTZCameraTester.PelcoConfiguration.SetConfigurationResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).SetConfiguration(inValue);
        }
        
        public void ResetConfiguration() {
            base.Channel.ResetConfiguration();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.RestartResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.Restart(PTZCameraTester.PelcoConfiguration.RestartRequest request) {
            return base.Channel.Restart(request);
        }
        
        public void Restart(string modelName) {
            PTZCameraTester.PelcoConfiguration.RestartRequest inValue = new PTZCameraTester.PelcoConfiguration.RestartRequest();
            inValue.modelName = modelName;
            PTZCameraTester.PelcoConfiguration.RestartResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).Restart(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.GetConfigurationResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.GetConfiguration(PTZCameraTester.PelcoConfiguration.GetConfigurationRequest request) {
            return base.Channel.GetConfiguration(request);
        }
        
        public PTZCameraTester.PelcoConfiguration.PelcoConfig GetConfiguration() {
            PTZCameraTester.PelcoConfiguration.GetConfigurationRequest inValue = new PTZCameraTester.PelcoConfiguration.GetConfigurationRequest();
            PTZCameraTester.PelcoConfiguration.GetConfigurationResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).GetConfiguration(inValue);
            return retVal.pelcoConfig;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.GetModelNameResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.GetModelName(PTZCameraTester.PelcoConfiguration.GetModelNameRequest request) {
            return base.Channel.GetModelName(request);
        }
        
        public string GetModelName() {
            PTZCameraTester.PelcoConfiguration.GetModelNameRequest inValue = new PTZCameraTester.PelcoConfiguration.GetModelNameRequest();
            PTZCameraTester.PelcoConfiguration.GetModelNameResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).GetModelName(inValue);
            return retVal.modelName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.GetModelNumberResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.GetModelNumber(PTZCameraTester.PelcoConfiguration.GetModelNumberRequest request) {
            return base.Channel.GetModelNumber(request);
        }
        
        public string GetModelNumber() {
            PTZCameraTester.PelcoConfiguration.GetModelNumberRequest inValue = new PTZCameraTester.PelcoConfiguration.GetModelNumberRequest();
            PTZCameraTester.PelcoConfiguration.GetModelNumberResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).GetModelNumber(inValue);
            return retVal.modelNumber;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.ResetSecurityResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.ResetSecurity(PTZCameraTester.PelcoConfiguration.ResetSecurityRequest request) {
            return base.Channel.ResetSecurity(request);
        }
        
        public void ResetSecurity(string modelName) {
            PTZCameraTester.PelcoConfiguration.ResetSecurityRequest inValue = new PTZCameraTester.PelcoConfiguration.ResetSecurityRequest();
            inValue.modelName = modelName;
            PTZCameraTester.PelcoConfiguration.ResetSecurityResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).ResetSecurity(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.ResetSyncedResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.ResetSynced(PTZCameraTester.PelcoConfiguration.ResetSyncedRequest request) {
            return base.Channel.ResetSynced(request);
        }
        
        public void ResetSynced(string modelName) {
            PTZCameraTester.PelcoConfiguration.ResetSyncedRequest inValue = new PTZCameraTester.PelcoConfiguration.ResetSyncedRequest();
            inValue.modelName = modelName;
            PTZCameraTester.PelcoConfiguration.ResetSyncedResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).ResetSynced(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PTZCameraTester.PelcoConfiguration.IsRegisteredResponse PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType.IsRegistered(PTZCameraTester.PelcoConfiguration.IsRegisteredRequest request) {
            return base.Channel.IsRegistered(request);
        }
        
        public int IsRegistered() {
            PTZCameraTester.PelcoConfiguration.IsRegisteredRequest inValue = new PTZCameraTester.PelcoConfiguration.IsRegisteredRequest();
            PTZCameraTester.PelcoConfiguration.IsRegisteredResponse retVal = ((PTZCameraTester.PelcoConfiguration.PelcoConfigurationPortType)(this)).IsRegistered(inValue);
            return retVal.isRegistered;
        }
    }
}
